go.mod, go.sum, internal/executor/executor_test.go, internal/executor/instance/instance.go, internal/executor/testdata/resource-limits/.cirrus.yml, internal/testutil/fs.go
=> Enforce CPU and memory limits

.golangci.yml, internal/executor/agent/agent.go, internal/executor/executor_test.go, internal/executor/instance/instance.go, internal/executor/rpc/rpc.go, internal/executor/testdata/additional-containers/.cirrus.yml, internal/testutil/executor.go, internal/testutil/fs.go
[Port mappings](https://cirrus-ci.org/guide/writing-tasks/#additional-containers) are not supported for now and the warning message is printed for each additional container that uses a port mapping.
=> Support additional containers

go.mod, go.sum, pkg/parser/parser.go
* use retries
* block until connection is established
* bundle certificates via gocertifi
Similar to how the agent dials the rpc endpoint
=> Improved gRPC dial

internal/executor/executor_test.go, internal/executor/instance/instance.go, internal/executor/testdata/entrypoint/.cirrus.yml
Entrypoint has a higher priority
=> Override entrypoint

internal/executor/build/build.go, internal/executor/build/command.go, internal/executor/build/commandstatus/commandstatus.go, internal/executor/build/task.go, internal/executor/build/task_test.go, internal/executor/executor_test.go, internal/executor/rpc/rpc.go, internal/executor/testdata/execution-behavior/.cirrus.yml
This essentially introduces per-command status fields and lets us answer the question of e.g. whether a task containing `ON_FAILURE` command is completed, failed and whatnot.
=> Support execution behavior on the CLI side

internal/commands/run.go, internal/executor/executor.go, internal/executor/executor_test.go, internal/executor/instance/container.go, internal/executor/instance/instance.go, internal/executor/instance/pipe.go, internal/executor/instance/volume.go, internal/executor/instance/volume_test.go, internal/executor/options.go, internal/executor/testdata/dirty-mode/.cirrus.yml, internal/testutil/executor.go
=> Dirty mode for running tasks

go.mod, go.sum, internal/commands/run.go, internal/commands/run_test.go, internal/executor/executor.go, internal/executor/executor_test.go, internal/executor/instance/container.go, internal/executor/instance/instance.go, internal/executor/instance/pipe.go, internal/executor/instance/volume.go, internal/executor/options.go, internal/executor/rpc/cache.go, internal/executor/rpc/options.go, internal/executor/rpc/rpc.go, internal/testutil/executor.go
=> Integrate Echelon

.golangci.yml, go.mod, go.sum, internal/commands/run_test.go, internal/executor/executor.go, internal/executor/executor_test.go, internal/executor/instance/instance.go, internal/executor/instance/prebuilt.go, internal/executor/instance/prebuilt_test.go, internal/executor/testdata/files-contents/.cirrus.yml, internal/executor/testdata/prebuilt-dockerfile/.cirrus.yml, internal/executor/testdata/prebuilt-dockerfile/docker/Dockerfile, pkg/parser/parser.go
=> Support Dockerfile as CI environment

internal/executor/build/build.go
So the order of execution is always the same
=> Stable order of task execution

INSTALL.md, README.md, intallation.md
Added a separate installation guide, added an example and some other stuff. @edigaryev what do you think?
=> Reworked documentation

INSTALL.md
=> Update install instructions for GitHub Actions

internal/commands/run.go
=> Ensure that the Docker daemon is reachable before running the tasks

.goreleaser.yml, internal/commands/root.go
=> Support --version flag

.goreleaser.yml, INSTALL.md, README.md
See https://goreleaser.com/customization/homebrew/
=> Homebrew Releases

go.mod, go.sum, internal/executor/instance/instance.go, internal/executor/rpc/rpc.go, internal/testutil/executor.go, pkg/parser/instance/container.go, pkg/parser/parser.go, pkg/parser/task/pipe.go, pkg/parser/task/task.go, pkg/rpcparser/parser_test.go
This will provide nice diffs in #69 and should improve the overall experience when working with the Task.instance field.
=> Switch to google.protobuf.Any-backed task instances

INSTALL.md
=> INSTALL.md: use Go modules when running go get

internal/commands/root.go
If version is explicitly not configured
=> Fall back to module version

INSTALL.md
=> INSTALL.md: mention that Docker is required

internal/commands/run.go
=> Support explicitly setting output format

internal/commands/run.go
=> Flag to use local YAML parser instead of the remote one

go.mod, pkg/larker/larker.go, pkg/larker/larker_test.go, pkg/larker/loader/git/bounded/bounded.go, pkg/larker/loader/git/bounded/bounded_test.go, pkg/larker/loader/git/git.go, pkg/larker/loader/git/git_test.go, pkg/larker/loader/loader.go, pkg/larker/testdata/load-git-helpers/.cirrus.star, pkg/larker/testdata/load-git-helpers/expected.yml
See #53.
Some things that still need to be taken care of:
* make Git-related storages bounded to a specific constant (e.g. 8 MiB)
https://github.com/cirruslabs/cirrus-cli/blob/04bbcae3addfcd5007460a26fad2e7353f40523d/pkg/larker/loader/git/git.go#L65-L66
* write a few more tests
=> Support loading Starlark modules from Git

internal/executor/environment/environment.go, internal/executor/environment/environment_test.go
=> Set CIRRUS_TAG environment variable if HEAD is tagged

internal/commands/run_test.go, internal/commands/testdata/run-task-filtering-by-label/.cirrus.yml, internal/executor/taskfilter/taskfilter.go
=> Task filtering by labels

internal/executor/instance/container.go, internal/executor/instance/pipe.go, internal/executor/instance/volume.go, internal/executor/instance/volume_test.go
Cleanup robustness in the presence of errors.
=> Volume cleanup improvements

internal/commands/run.go, internal/commands/run_test.go, internal/commands/testdata/run-no-cleanup/.cirrus.yml, internal/executor/instance/container.go, internal/executor/instance/instance.go, internal/executor/instance/pipe.go, internal/executor/options/docker.go
=> Option to keep containers after execution for debugging

pkg/parser/instance/additionalcontainer.go, pkg/parser/labels.go, pkg/parser/modifier/matrix/expander.go, pkg/parser/modifier/matrix/matrix.go, pkg/parser/modifier/matrix/matrix_test.go, pkg/parser/modifier/matrix/testdata/one-sized-matrix.yaml, pkg/parser/modifier/matrix/testdata/parallel.yaml, pkg/parser/node/finder.go, pkg/parser/options.go, pkg/parser/parser.go, pkg/parser/parser_test.go, pkg/parser/task/command.go, pkg/parser/task/default.go, pkg/parser/task/pipe.go, pkg/parser/task/piperesources.go, pkg/parser/task/task.go, pkg/parser/testdata/via-rpc/matrix-complex.json, pkg/parser/testdata/via-rpc/matrix-complex.yml, pkg/parser/testdata/via-rpc/matrix-env.json, pkg/parser/testdata/via-rpc/matrix-env.yml, pkg/parser/testdata/via-rpc/matrix-nested.json, pkg/parser/testdata/via-rpc/matrix-nested.yml, pkg/parser/testdata/via-rpc/matrix-puppeteer.fc, pkg/parser/testdata/via-rpc/matrix-puppeteer.json, pkg/parser/testdata/via-rpc/matrix-puppeteer.yml, pkg/parser/testdata/via-rpc/matrix-script.json, pkg/parser/testdata/via-rpc/matrix-script.yml, pkg/parser/testdata/via-rpc/pipe-simple.json, pkg/parser/testdata/via-rpc/pipe-simple.yml
=> More RPC-parser-powered tests: matrix and pipe

internal/commands/internal/internal.go, internal/commands/internal/test.go, internal/commands/internal/test_test.go, internal/commands/internal/testdata/test-simple/dir/subdir/.cirrus.expected.yml, internal/commands/internal/testdata/test-simple/dir/subdir/.cirrus.star, internal/commands/internal/testdata/test-simple/lib.star, internal/commands/logs/output.go, internal/commands/root.go, internal/commands/run.go
=> Introduce internal test command

INSTALL.md, README.md, internal/executor/heuristic/heuristic.go, internal/executor/instance/instance.go, internal/executor/rpc/heuristic.go, internal/executor/rpc/rpc.go
=> Cloud Build support

STARLARK.md
=> Starlark documentation

Dockerfile, internal/commands/serve.go
Plus allow to pass a port via an environment variable
=> Pick a port for serving from environment

README.md, internal/executor/instance/volume.go
Also make sure it has a friendly name.
See #124.
=> Always cleanup helper container

internal/executor/instance/prebuilt.go
=> Reuse already prebuilt images from GCR

STARLARK-TEMPLATING.md
=> Starlark templating guide

internal/executor/instance/volume.go
To fix the bug with log timestamps
=> Agent 1.18.1

go.mod, go.sum, internal/commands/logs/output.go
=> noemoji output format

internal/executor/instance/containerbackend/containerbackend.go, internal/executor/instance/containerbackend/docker_unsupported.go, internal/executor/instance/containerbackend/podman.go, internal/executor/instance/containerbackend/unimplemented.go
Some test fail due to Podman not being fully implemented.
=> Fix tests on non-Linux platforms

internal/executor/executor.go, internal/executor/instance/instance.go, internal/executor/instance/persistentworker.go, internal/executor/instance/persistentworker_test.go, internal/executor/instance/volume.go, internal/executor/instance/volume_test.go
=> Respect custom agent version (CIRRUS_AGENT_VERSION)

internal/executor/executor.go, internal/executor/executor_test.go, internal/executor/testdata/custom-cirrus-working-dir/.cirrus.yml
=> Fully respect CIRRUS_WORKING_DIR environment variable

internal/commands/helpers/helpers.go, internal/commands/run_test.go, internal/commands/validate/validate.go, internal/commands/validate_test.go, internal/evaluator/evaluator.go, internal/evaluator/evaluator_test.go
See https://github.com/cirruslabs/cirrus-cli/issues/174.
=> Support .cirrus.yaml too

go.mod, go.sum, internal/commands/worker/run.go, internal/worker/options.go, internal/worker/task.go, internal/worker/worker.go, internal/worker/worker_test.go
=> cirrus worker run: ability to override RPC endpoint

.golangci.yml, .goreleaser.yml
See https://github.com/cirruslabs/cirrus-ci-docs/issues/263#issuecomment-732192654.
=> .goreleaser.yml: build for s390x and ppc64le

internal/executor/instance/persistentworker.go, internal/executor/instance/volume.go
=> Agent 1.23.1

.cirrus.yml
Via gotip
Will test binary on Friday when the new Mac Mini should arrive.
Related issues: https://github.com/golang/go/issues/42684
Fixes #171
=> Build for Apple Silicon

.cirrus.star, .cirrus.yml
Empty for now (should be merged with the YAML).
=> Add .cirrus.star

internal/worker/task.go
Plus don't fail execution if failed to notify server
=> Include secret in task identity

internal/commands/run.go, internal/commands/run_test.go, internal/commands/testdata/docker-no-pull/.cirrus.yml, internal/executor/instance/instance.go, internal/executor/options/container.go, internal/executor/options/container_test.go
=> --container-pull flag and IfNotPresent semantics by default

INSTALL.md, README.md
=> Document Podman

pkg/parser/parseable/parseable.go, pkg/parser/parser_test.go, pkg/parser/task/task.go, pkg/parser/testdata/collectible-order.json, pkg/parser/testdata/collectible-order.yml
=> Second pass to evaluate collectibles in declaration order

go.mod, go.sum, pkg/parser/parser_test.go, pkg/parser/testdata/yaml-12-booleans-only.json, pkg/parser/testdata/yaml-12-booleans-only.yml
To be compatible with the Cirrus Cloud parser.
=> Support YAML 1.2 spec booleans only

pkg/parser/node/finder.go, pkg/parser/node/finder_test.go, pkg/parser/node/node.go, pkg/parser/parseable/parseable.go, pkg/parser/testdata/via-rpc/new-deduplicator-different-type.json, pkg/parser/testdata/via-rpc/new-deduplicator-different-type.yml, pkg/parser/testdata/via-rpc/new-deduplicator-same-type.json, pkg/parser/testdata/via-rpc/new-deduplicator-same-type.yml
Needed for Cirrus Cloud parser compatibility.
=> Parser deduplicator

go.mod, go.sum
To fix the build on Apple Silicon.
See https://github.com/otiai10/copy/pull/42.
=> Bump github.com/otiai10/copy

.cirrus.yml
It seems it's getting rate limited on Docker Hub
=> Don't use Gorelease image

internal/executor/instance/persistentworker/isolation/parallels/parallels.go
So customizations in `~/.zprofile` are picked.
/cc @edigaryev
=> Use login shell for Parallels VMs

internal/executor/platform/platform.go
=> Cirrus Agent 1.26.0

internal/commands/worker/run.go
To simplify the default configuration
FYI @edigaryev
=> Make the default worker name pretty

PERSISTENT-WORKERS.md
=> Updated defaults for name labels

pkg/parser/node/node.go, pkg/parser/testdata/via-rpc/new-collectible-env-merging-to-list.json, pkg/parser/testdata/via-rpc/new-collectible-env-merging-to-list.yml, pkg/parser/testdata/via-rpc/new-collectible-env-merging-to-map.json, pkg/parser/testdata/via-rpc/new-collectible-env-merging-to-map.yml
Otherwise they get overwritten with each other.
=> Properly merge "env" and "environment" fields of different types

pkg/parser/task/command/cache.go, pkg/parser/task/dockerbuilder.go, pkg/parser/task/task.go, pkg/parser/testdata/via-rpc/new-docker-builder-cache-is-uploaded.json, pkg/parser/testdata/via-rpc/new-docker-builder-cache-is-uploaded.yml
Also move upload command generation into a separate function.
=> Generate cache upload commands for docker_builder tasks too

internal/evaluator/evaluator.go, pkg/parser/options.go, pkg/parser/parser.go, pkg/parser/parser_test.go, pkg/parser/task/base.go, pkg/parser/task/dockerbuilder.go, pkg/parser/task/pipe.go, pkg/parser/task/task.go, pkg/parser/testdata/cirrus.json, pkg/parser/testdata/proto-task-properties.json, pkg/parser/testdata/proto-task-properties.yml, pkg/parser/testdata/via-rpc/execution-behavior.json, pkg/parser/testdata/via-rpc/execution-behavior.yml, pkg/parser/testdata/via-rpc/simple-taskDependencies.json, pkg/parser/testdata/via-rpc/simple-taskDependencies.yml, pkg/parser/testdata/via-rpc/simple-topLevelDefinitions.json, pkg/parser/testdata/via-rpc/simple-topLevelDefinitions.yml, pkg/parser/testdata/via-rpc/simple-twoTasks.json, pkg/parser/testdata/via-rpc/simple-twoTasks.yml
Also ran cloud converter tests agains this branch. Will create a PR to Cirrus CI shortly.
=> Support custom task properties via RPC call

pkg/parser/boolevator/boolevator.go, pkg/parser/boolevator/operator.go, pkg/parser/boolevator/operator_test.go, pkg/parser/expander/expander.go, pkg/parser/expander/expander_test.go, pkg/parser/node/accessor.go, pkg/parser/node/accessor_test.go
For compatibility with the Cirrus Cloud parser.
=> Boolevator: pre-expand environment variables

PERSISTENT-WORKERS.md, go.mod, go.sum, internal/commands/worker/run.go, internal/worker/options.go
=> Worker: support log rotation and levels configuration

.cirrus.yml
=> [ci] more resources for release tasks

PERSISTENT-WORKERS.md, internal/commands/worker/run.go
=> Fixed rotate-size handling

internal/executor/instance/persistentworker/isolation/parallels/parallels.go
=> Context cancellation for SSH connection to Parallels VMs

pkg/parser/node/node.go, pkg/parser/testdata/via-rpc/new-scripts-with-null-array-scalar.json, pkg/parser/testdata/via-rpc/new-scripts-with-null-array-scalar.yml
To provide the backwards compatibility with the Cloud parser.
=> Parser: filter out null scalars in YAML arrays

internal/executor/executor.go, internal/executor/executor_internal_test.go
=> Executor: properly extract hash from the Dockerfile image name

.cirrus.yml
Since Podman freaks about it. Fixes https://github.com/cirruslabs/cirrus-cli/issues/260
=> Remove Docker Config for Podman tests

internal/executor/instance/containerbackend/containerbackend.go, internal/executor/instance/containerbackend/docker.go, internal/executor/instance/containerbackend/podman_linux.go, internal/executor/instance/containerbackend/unroll.go, internal/executor/instance/prebuilt.go, internal/executor/options/container.go
Should help with the issues in #256.
=> Assorted prebuilt instance fixes

.cirrus.yml, internal/worker/worker_test.go
Via a persistent worker with Docker and Parallels installed
=> Test on macOS

pkg/parser/node/accessor.go, pkg/parser/testdata/via-rpc/new-env-map-with-list-values.json, pkg/parser/testdata/via-rpc/new-env-map-with-list-values.yml
Flatten them into a single value.
=> Parser: support env/environment maps with list values

internal/executor/instance/persistentworker/isolation/parallels/clone.go, internal/executor/instance/persistentworker/isolation/parallels/parallels.go, internal/executor/instance/persistentworker/isolation/parallels/server.go, internal/executor/instance/persistentworker/isolation/parallels/vm.go
Multiple changes in separate commits for clarity
=> Parallels: cleanup & error message fixes

internal/commands/run.go, internal/commands/validate/validate.go, internal/executor/executor_test.go, internal/testutil/executor.go
Now that we have #276 and #280 and the metrics are looking somewhat stable, we should probably do the switch and see if it works.
Resolves #251.
=> Use Go parser by default

pkg/parser/instance/proto.go
=> Don't look into repeated fields for platform

.cirrus.yml, internal/commands/testdata/run-no-cleanup/.cirrus.yml, internal/executor/executor_test.go, internal/executor/instance/containerbackend/containerbackend.go, internal/executor/instance/containerbackend/docker.go, internal/executor/instance/containerbackend/podman_linux.go, internal/executor/instance/containerbackend/unimplemented.go, internal/executor/instance/instance.go, internal/executor/testdata/additional-containers/.cirrus.yml, internal/executor/testdata/container-logs/.cirrus.yml
=> Stream launched container's logs to the CLI's logger

internal/executor/build/build.go, internal/executor/build/build_test.go, internal/executor/build/task.go, internal/executor/build/task_test.go, internal/executor/executor.go, internal/executor/executor_darwin_test.go, internal/executor/executor_test.go, internal/executor/instance/instance.go, internal/executor/instance/persistentworker/isolation/parallels/options.go, internal/executor/instance/persistentworker/isolation/parallels/parallels.go, internal/executor/instance/persistentworker/persistentworker.go, internal/logger/logger.go, internal/worker/task.go, pkg/rpcparser/parser.go
=> Stream VM' logs when executing with Parallels isolation

internal/commands/run_test.go
It's the only test that should actually force pull the image.
=> Fix TestRunContainerPull test

internal/commands/run.go, internal/commands/validate/validate.go, internal/executor/build/task.go, internal/executor/instance/instance.go, pkg/parser/labels.go, pkg/parser/options.go, pkg/parser/parser.go, pkg/parser/parser_test.go, pkg/parser/task/task.go, pkg/parser/testdata/missing-instances.yml
=> Partially fix "cirrus {run,validate}" error on unsupported instances

pkg/parser/node/accessor.go, pkg/parser/testdata/via-rpc/new-script-with-ambiguous-list-of-maps.json, pkg/parser/testdata/via-rpc/new-script-with-ambiguous-list-of-maps.yml
This provides compatibility with the cloud parser.
=> Parser: minimally support scripts with a list of maps

pkg/parser/instance/additionalcontainer.go, pkg/parser/instance/container.go, pkg/parser/node/accessor.go, pkg/parser/task/base.go, pkg/parser/task/pipe.go, pkg/parser/testdata/via-rpc/new-docker-arguments-as-list.json, pkg/parser/testdata/via-rpc/new-docker-arguments-as-list.yml
=> Parser: allow list of maps in docker_arguments

pkg/parser/boolevator/boolevator_test.go
Related issue: https://github.com/cirruslabs/cirrus-ci-docs/issues/290
=> Additional test case where Kotlin boolevator was failing

.cirrus.yml, pkg/larker/fs/github/github_test.go
To work around API rate limits.
=> Disable GitHub API tests on macOS instance

pkg/parser/boolevator/boolevator.go, pkg/parser/boolevator/boolevator_test.go, pkg/parser/testdata/via-rpc/new-boolevator-handles-multiline-only-if.yml
...and not in string scope as it was before.
=> Boolevator: only support newlines in the expression scope

pkg/parser/instance/proto.go
=> Parser: fix docker_arguments handling when using additional instances

internal/commands/validate/validate.go, internal/evaluator/evaluator.go, pkg/executorservice/executorservice.go
=> cirrus validate: query additional instances from the RPC

internal/commands/validate/testdata/cloud-instance/.cirrus.yml, internal/commands/validate/validate_test.go
Follow-up to https://github.com/cirruslabs/cirrus-cli/pull/304.
=> cirrus validate: ensure additional instances are fetched without errors

pkg/parser/modifier/matrix/matrix.go, pkg/parser/parser_test.go, pkg/parser/testdata/via-rpc/pipe-matrix.json, pkg/parser/testdata/via-rpc/pipe-matrix.yml
Fixes https://github.com/cirruslabs/cirrus-ci-docs/issues/802
=> Support matrix modification in pipes

internal/executor/build/task.go, internal/executor/executor_test.go, internal/executor/instance/container.go, internal/executor/instance/instance.go, internal/executor/instance/persistentworker/isolation/parallels/parallels.go, internal/executor/instance/persistentworker/isolation/parallels/sftp.go, internal/executor/instance/pipe.go, internal/executor/instance/volume.go, internal/executor/instance/volume_test.go, internal/executor/platform/platform.go, internal/executor/platform/unix.go, internal/executor/platform/windows.go, internal/executor/testdata/custom-cirrus-working-dir/.cirrus.yml, pkg/rpcparser/parser.go
=> Respect CIRRUS_WORKING_DIR when using containers

pkg/parser/labels.go, pkg/parser/testdata/via-rpc/new-empty-labels-are-filtered.json, pkg/parser/testdata/via-rpc/new-empty-labels-are-filtered.yml
Compatibility with the Cirrus Cloud parser.
=> Parser: filter out instance labels with empty values

pkg/parser/instance/windowscontainer.go, pkg/parser/testdata/via-rpc/new-windows-container-default-os-version.json, pkg/parser/testdata/via-rpc/new-windows-container-default-os-version.yml
Compatibility with the Cirrus Cloud parser.
=> Parser: set default Windows container OS version to 2019

go.mod, go.sum, internal/evaluator/evaluator.go, internal/evaluator/evaluator_test.go
Draft because we need to implement support in the consumer first.
=> Evaluator: recognize and process rich errors

internal/evaluator/evaluator.go
=> cirrus serve: send X-Cirrus-Evaluator-Version header for all responses

internal/executor/executor.go, internal/executor/taskfilter/taskfilter.go
=> cirrus run: error out when no tasks match the filter

internal/executor/instance/persistentworker/isolation/none/none.go, internal/executor/platform/platform.go
To pick up https://github.com/cirruslabs/cirrus-ci-agent/pull/112
=> Bump Agent Version

internal/executor/instance/runconfig/runconfig.go, internal/executor/instance/runconfig/runconfig_test.go, internal/worker/task.go
=> Persistent worker: don't downgrade agent's version

internal/executor/platform/platform.go
See https://github.com/cirruslabs/cirrus-cli/issues/357#issuecomment-814082010.
=> Bump default agent's version to 1.38.1

internal/worker/task.go
Makes sure we signal task completion correctly and improves UX (no more `failed to notify the server about the stopped task` in logs), because previously worker was trying to call gRPC methods with an already cancelled context.
=> Persistent worker: use separate context to send task notifications

go.mod, go.sum, internal/executor/instance/instance.go, pkg/parser/instance/additionalcontainer.go, pkg/parser/schema/schema.go, pkg/parser/testdata/cirrus.json, pkg/parser/testdata/example-mysql.json, pkg/parser/testdata/proto-instance.json, pkg/parser/testdata/via-rpc/new-deduplicator-same-type.json, pkg/parser/testdata/via-rpc/simple-additionalContainers.json
See https://github.com/cirruslabs/cirrus-ci-docs/issues/810.
=> Support multiple port mappings on additional_containers

go.mod, go.sum, pkg/larker/loader/git/git.go, pkg/larker/loader/git/git_test.go, pkg/larker/testdata/load-git-helpers/.cirrus.star
=> Larker: fetch the specified branch (if any) before switching to it

go.mod, go.sum, internal/evaluator/evaluator_test.go, pkg/parser/node/yaml.go, pkg/parser/node/yaml_test.go, pkg/parser/parser_test.go
=> Parser: fix line and column reporting in YAML

.golangci.yml, internal/executor/executor_test.go, internal/executor/instance/persistentworker/isolation/none/none.go, internal/executor/instance/persistentworker/isolation/none/options.go, internal/executor/instance/persistentworker/persistentworker.go, internal/executor/platform/platform.go, internal/executor/testdata/persistent-worker-graceful-termination/.cirrus.yml, internal/testutil/executor.go
=> Persistent worker with none isolation: gracefully terminate agent

go.mod, go.sum, internal/evaluator/evaluator.go, internal/evaluator/evaluator_test.go, pkg/larker/errexecfailed.go, pkg/larker/extendederror.go, pkg/larker/larker.go, pkg/parser/parser.go, pkg/parser/parser_test.go
Resolves https://github.com/cirruslabs/cirrus-cli/issues/377.
=> Starlark: provide backtraces in logs

internal/executor/executor.go
=> Always finish executor logger

pkg/larker/larker.go, pkg/larker/larker_test.go, pkg/larker/testdata/no-ctx/.cirrus.star, pkg/larker/testdata/no-ctx/expected.yaml, pkg/larker/testdata/simple-task/.cirrus.star
=> Starlark's main(): make ctx argument optional

pkg/larker/larker.go, pkg/larker/larker_test.go, pkg/larker/testdata/no-ctx/.cirrus.star
A follow-up to https://github.com/cirruslabs/cirrus-cli/pull/393#issuecomment-845045856.
=> Starlark hooks: make ctx argument optional

go.mod, go.sum, pkg/larker/fs/cachinglayer/cachelayer.go, pkg/larker/fs/cachinglayer/cachelayer_test.go, pkg/larker/larker.go
=> Larker: cache FS operations

.golangci.yml, internal/commands/internal/test/test.go, internal/commands/internal/test/test_test.go, internal/commands/internal/test/testdata/report/.cirrus.expected.log, internal/commands/internal/test/testdata/report/.cirrus.expected.yml, internal/commands/internal/test/testdata/report/.cirrus.star, internal/commands/internal/test/testdata/report/report-expected.json
Resolves https://github.com/cirruslabs/cirrus-cli/issues/397.
=> Implement cirrus internal test's --report flag

go.mod, go.sum, internal/executor/build/taskstatus/taskstatus.go, internal/executor/executor.go, internal/executor/executor_test.go, internal/executor/instance/instance.go, internal/executor/instance/unsupported.go
=> cirrus run: skip unsupported instances instead of failing the build

.golangci.yml, internal/executor/executor.go
=> cirrus run: keep running tasks even if there are failed ones

pkg/parser/parser_test.go, pkg/parser/testdata/no-always-override.json, pkg/parser/testdata/no-always-override.yml
Needed to ensure proper behavior for https://github.com/cirruslabs/cirrus-ci-docs/issues/880.
=> test(parser): ensure that "always:" blocks stack up nicely

pkg/parser/parser.go, pkg/parser/parser_test.go, pkg/parser/testdata/issues/multiple-name-ambiguity.yml, pkg/parser/testdata/issues/no-multiple-name-ambiguity.yml
Resolves https://github.com/cirruslabs/cirrus-cli/issues/427.
=> Add a warning when task name is overriden

pkg/parser/parser_test.go, pkg/parser/testdata/cirrus.json
To simplify the updating process.
=> Parser: use CLI's schema as a reference

pkg/parser/parser_test.go, pkg/parser/task/base.go, pkg/parser/task/behavior.go, pkg/parser/task/command/cache.go, pkg/parser/task/command/uploadcaches.go, pkg/parser/task/dockerbuilder.go, pkg/parser/task/pipe.go, pkg/parser/task/pipestep.go, pkg/parser/task/task.go, pkg/parser/testdata/cirrus.json, pkg/parser/testdata/invalid-upload-caches-nonexistent-cache.yml, pkg/parser/testdata/pipe-cache.json, pkg/parser/testdata/pipe-cache.yml, pkg/parser/testdata/upload-caches.json, pkg/parser/testdata/upload-caches.yml
See https://github.com/cirruslabs/cirrus-ci-docs/issues/880#issuecomment-879041602.
=> Parser: introduce upload_caches virtual instruction

go.mod, go.sum, pkg/parser/parser_test.go, pkg/parser/task/command/cache.go, pkg/parser/testdata/cache-fingerprint-key.json, pkg/parser/testdata/cache-fingerprint-key.yml, pkg/parser/testdata/cirrus.json, pkg/parser/testdata/invalid-cache-two-fingerprints.yml
See https://github.com/cirruslabs/cirrus-ci-docs/issues/867.
=> Support explicit cache key via fingerprint_key: field

internal/commands/run.go, internal/commands/run_test.go, internal/commands/testdata/run-affected-files/.cirrus.yml
=> cirrus run: new --affected-files flag

pkg/parser/parser.go, pkg/parser/parser_test.go
Resolves https://github.com/cirruslabs/cirrus-ci-docs/issues/885.
=> Parser: clarify task name override warning message

pkg/parser/bfunc.go, pkg/parser/bfunc_test.go, pkg/parser/parser.go
Fixes https://github.com/cirruslabs/cirrus-ci-docs/issues/873
=> Introduce changesIncludeOnly function

STARLARK-MODULES.md, pkg/larker/larker_test.go, pkg/larker/loader/builtin.go, pkg/larker/loader/loader.go, pkg/larker/testdata/builtin-changes-include-only/.cirrus.star, pkg/parser/bfunc.go, pkg/parser/bfunc_test.go
Resolves https://github.com/cirruslabs/cirrus-cli/issues/439. 
Also includes a few improvements on top of https://github.com/cirruslabs/cirrus-cli/pull/438.
=> Starlark: introduce changes_include_only built-in

internal/commands/helpers/git.go, internal/commands/helpers/git_extra.go, internal/commands/helpers/git_test.go, internal/commands/run.go
Resolves https://github.com/cirruslabs/cirrus-cli/issues/437.
=> Introduce --affected-files-git and --affected-files-git-cached

internal/commands/internal/test/test.go, internal/commands/internal/test/test_unsupported.go, internal/commands/run.go, internal/commands/run_test.go, internal/commands/run_unsupported.go, internal/commands/serve.go, internal/commands/serve_unsupported.go, internal/evaluator/evaluator.go, internal/evaluator/evaluator_test.go, internal/executor/executor_linux_test.go, internal/executor/executor_test.go, internal/executor/heuristic/heuristic.go, internal/executor/heuristic/heuristic_unsupported.go, internal/executor/instance/containerbackend/docker.go, internal/executor/instance/containerbackend/docker_unsupported.go, internal/executor/instance/containerbackend/podman.go, internal/executor/instance/persistentworker/isolation/parallels/copy.go, internal/executor/instance/persistentworker/isolation/parallels/vmkiller_unsupported.go, internal/executor/platform/auto.go, internal/executor/platform/auto_windows.go, pkg/larker/fs/github/github.go, pkg/larker/fs/github/github_test.go, pkg/larker/fs/normalize.go, pkg/parser/parser.go
Should ease GitHub API usage in https://github.com/cirruslabs/cirrus-cli/pull/452 a bit.
=> Parser: wrap the final file system in a caching layer

internal/evaluator/evaluator.go
Needed for the functional tests to work.
=> Evaluator: respect filesContents

pkg/parser/dockerfile.go, pkg/parser/parser_test.go
=> Don't completely fail on failing to retrieve file

pkg/parser/dockerfile.go, pkg/parser/parser_test.go, pkg/parser/testdata/additional-instance-dockerfile-hashing.json, pkg/parser/testdata/additional-instance-dockerfile-hashing.yml
=> Parser: respect CIRRUS_DOCKER_CONTEXT

pkg/parser/dockerfile.go, pkg/parser/instance/additionalcontainer.go, pkg/parser/instance/container.go, pkg/parser/instance/isolation/container.go, pkg/parser/instance/isolation/isolation.go, pkg/parser/instance/isolation/parallels.go, pkg/parser/instance/persistentworker.go, pkg/parser/instance/proto.go, pkg/parser/instance/windowscontainer.go, pkg/parser/issue/registry.go, pkg/parser/node/node.go, pkg/parser/parseable/parseable.go, pkg/parser/parser.go, pkg/parser/parser_test.go, pkg/parser/parserkit/parserkit.go, pkg/parser/task/base.go, pkg/parser/task/behavior.go, pkg/parser/task/command/artifacts.go, pkg/parser/task/command/cache.go, pkg/parser/task/command/file.go, pkg/parser/task/dockerbuilder.go, pkg/parser/task/pipe.go, pkg/parser/task/piperesources.go, pkg/parser/task/pipestep.go, pkg/parser/task/task.go, pkg/parser/testdata/problematic-artifacts-instruction-is-not-a-map.yml
See https://github.com/cirruslabs/cirrus-ci-docs/issues/913.
=> Parser: emit a warning when on potential field misuse

pkg/parser/instance/container.go, pkg/parser/instance/proto.go, pkg/parser/node/accessor.go, pkg/parser/parser_test.go, pkg/parser/testdata/docker-arguments-expansion.json, pkg/parser/testdata/docker-arguments-expansion.yml
To avoid the issue spotted in https://github.com/containers/image/pull/1368/files#diff-62587956f943bb2503db7bc6dd27d0d888074a1c0ecaab3f570ad611aff0f7bb.
=> Parser: expand docker arguments

pkg/parser/task/dockerbuilder.go, pkg/parser/task/pipe.go, pkg/parser/task/task.go, pkg/parser/testdata/via-rpc/container_build-arguments.json, pkg/parser/testdata/via-rpc/container_build-complexArguments.json, pkg/parser/testdata/via-rpc/container_build-context.json, pkg/parser/testdata/via-rpc/container_build-osVersion.json, pkg/parser/testdata/via-rpc/container_build-simple.json, pkg/parser/testdata/via-rpc/container_build-twoTasksSameContainer.json, pkg/parser/testdata/via-rpc/environment-complex4.json, pkg/parser/testdata/via-rpc/matrix-nested.json, pkg/parser/testdata/via-rpc/matrix-puppeteer.json, pkg/parser/testdata/via-rpc/new-alias-reuse.json, pkg/parser/testdata/via-rpc/new-docker-arguments-as-list.json, pkg/parser/testdata/via-rpc/new-duplicate-task-names-are-kept.json, pkg/parser/testdata/via-rpc/new-empty-labels-are-filtered.json, pkg/parser/testdata/via-rpc/simple-additionalContainers.json, pkg/parser/testdata/via-rpc/simple-taskAliasDependencies.json
Otherwise the value is lost and https://github.com/cirruslabs/cirrus-ci-docs/issues/931 is not possible.
Plus regenerated fixtures to have all the map keys in order.
=> Add alias value to task properties

internal/executor/cache/cache.go, internal/executor/cache/cache_test.go
=> Cache tests: remove created blobs from disk

pkg/larker/fs/git/git.go, pkg/larker/larker.go, pkg/larker/loader/loader.go, pkg/larker/loader/module_fs.go
Explained the rationale behind the changes in the commit messages comments.
=> Git FS improvements

pkg/parser/dockerfile.go, pkg/parser/dockerfile_test.go
=> Parser: fix find() list iteration to calculate proper Dockerfile hashes

pkg/parser/node/matrix.go, pkg/parser/node/yaml.go, pkg/parser/parser_test.go, pkg/parser/testdata/yaml-merge-sequence.json, pkg/parser/testdata/yaml-merge-sequence.yml
Resolves https://github.com/cirruslabs/cirrus-ci-docs/issues/980 (more specifically https://github.com/cirruslabs/cirrus-ci-docs/issues/980#issuecomment-1078420628).
=> Parser: support sequences in YAML merge

pkg/parser/instance/additionalcontainer.go, pkg/parser/parser_test.go, pkg/parser/testdata/additional-container-port-and-ports-are-optional.json, pkg/parser/testdata/additional-container-port-and-ports-are-optional.yml
See https://github.com/cirruslabs/cirrus-ci-docs/issues/992.
=> Parser: do not require additional container's port: or ports:

Dockerfile, cloudbuild.yaml
Copied over from the [agent's Cloud Build config](https://github.com/cirruslabs/cirrus-ci-agent/blob/master/cloudbuild.yaml).
=> Multiarch Docker Builds

LICENSE
We are planning to open source quite a few projects which will be integrated between each other including Cirrus CLI. We believe AGPL is the best license for devtools because companies are tent to modify such tools for their needs and not always share the modifications with the community.
=> Switch license from MPL-2.0 to AGPL-3.0

go.mod, go.sum, internal/evaluator/evaluator_test.go, internal/executor/executor_darwin_test.go, internal/executor/instance/instance.go, internal/executor/instance/persistentworker/persistentworker.go, internal/worker/worker.go, internal/worker/worker_test.go, pkg/parser/instance/isolation/tart.go, pkg/parser/instance/macosinstance.go, pkg/parser/instance/proto.go, pkg/parser/parser_test.go, pkg/parser/task/task.go, pkg/parser/testdata/cirrus.json, pkg/parser/testdata/via-rpc/new-persistentworker-isolation-tart.yml, pkg/parser/testdata/via-rpc/simple-macos-instance.json, pkg/parser/testdata/via-rpc/simple-macos-instance.yml
=> Support running tasks in Tart VMs locally

internal/worker/task.go
Otherwise the task is just hanging assigned to the task and cancelation doesn't work.
=> Fail task if failed to create an instance

internal/executor/executor_darwin_test.go, internal/executor/instance/persistentworker/isolation/parallels/parallels.go, internal/executor/instance/persistentworker/isolation/tart/tart.go, internal/executor/instance/persistentworker/remoteagent/remoteagent.go
No symlinks/hardlinks/devices and sockets support yet.
=> Executor: synchronize working directory using SFTP when running Tart

.cirrus.yml
=> Use remote Tart VM

PERSISTENT-WORKERS.md, go.mod, go.sum, internal/commands/worker/config.go, internal/worker/options.go, internal/worker/worker.go, pkg/parser/instance/persistentworker.go, pkg/parser/node/accessor.go, pkg/parser/parser_test.go, pkg/parser/testdata/cirrus.json, pkg/parser/testdata/persistent-worker-resource-management.json, pkg/parser/testdata/persistent-worker-resource-management.yml
See https://github.com/cirruslabs/cirrus-cli/issues/504.
=> Support resource management for persistent worker mode

pkg/parser/boolevator/boolevator_test.go
For https://github.com/cirruslabs/cirrus-ci-docs/issues/1016
=> Extra boolevator test case

internal/commands/run.go, internal/commands/run_test.go, internal/commands/testdata/run-artifacts-dir/.cirrus.yml, internal/executor/executor.go, internal/executor/options.go, internal/executor/pathsafe/pathsafe.go, internal/executor/pathsafe/pathsafe_test.go, internal/executor/platform/platform.go, internal/executor/rpc/artifacts.go, internal/executor/rpc/noop.go, internal/executor/rpc/options.go, internal/executor/rpc/rpc.go, pkg/parser/task/base.go
Resolves https://github.com/cirruslabs/cirrus-cli/issues/526.
=> cirrus run: introduce --artifacts-dir

pkg/parser/task/task.go
Resolves https://github.com/cirruslabs/cirrus-ci-docs/issues/1043.
=> Parser: improve "task has no instance attached" error

pkg/parser/parser.go, pkg/parser/parser_test.go, pkg/parser/task/dockerbuilder.go, pkg/parser/task/pipe.go, pkg/parser/task/task.go, pkg/parser/task/tasklike.go, pkg/parser/testdata/issues-unbalanced-only-if-prevent.yml, pkg/parser/testdata/issues-unbalanced-only-if.yml
Resolves https://github.com/cirruslabs/cirrus-cli/issues/521.
=> Parser: unbalanced only_if:'s linter

pkg/parser/constants/constants.go, pkg/parser/dockerfile.go, pkg/parser/task/task.go
Resolves https://github.com/cirruslabs/cirrus-cli/issues/550.
=> Consider CIRRUS_ARCH when calculating Dockerfile hash

internal/executor/instance/persistentworker/isolation/tart/tart.go, internal/executor/instance/persistentworker/isolation/tart/vm.go
Resolves #554.
Related: https://github.com/cirruslabs/tart/issues/224.
=> cirrus run: support --dirty for Tart-based instances

pkg/larker/builtin/fs.go, pkg/larker/larker_test.go, pkg/larker/loader/loader.go, pkg/larker/resolver/module_fs.go, pkg/larker/resolver/module_fs_test.go, pkg/larker/testdata/dynamic-fs-resolution/.cirrus.star
See https://github.com/cirruslabs/cirrus-cli/issues/553.
=> Larker: dynamic FS resolution

go.mod, go.sum, internal/commands/worker/config.go, internal/commands/worker/pause.go, internal/commands/worker/resume.go, internal/commands/worker/run.go, internal/worker/options.go, internal/worker/task.go, internal/worker/upstream/grpc.go, internal/worker/upstream/options.go, internal/worker/upstream/upstream.go, internal/worker/worker.go, internal/worker/worker_test.go
Resolves https://github.com/cirruslabs/cirrus-cli/issues/561.
=> Persistent Workers: multi-upstream support

STARLARK-MODULES.md, internal/commands/internal/test/test.go
Resolves https://github.com/cirruslabs/cirrus-ci-docs/issues/1092.
=> Document how private Starlark modules can be tested

internal/executor/instance/persistentworker/isolation/tart/tart.go, internal/worker/worker.go
Resolves https://github.com/cirruslabs/cirrus-cli/issues/571.
=> Worker: cleanup Tart VMs on startup

internal/commands/internal/test/test_test.go, internal/commands/internal/test/testdata/complex-load-chain/dir/subdir/.cirrus.star, internal/commands/internal/test/testdata/complex-load-chain/emotions/emotions.star, internal/commands/internal/test/testdata/complex-load-chain/feelings/feelings.star, internal/commands/internal/test/testdata/complex-load-chain/lib.star, internal/commands/internal/test/testdata/complex-load-chain/logic.star, pkg/larker/fs/scopedlayer/scopedlayer.go, pkg/larker/resolver/module_fs.go
Resolves https://github.com/cirruslabs/cirrus-cli/issues/579.
=> Larker: scope relative FS calls

internal/executor/instance/persistentworker/isolation/tart/vm.go
See https://github.com/cirruslabs/tart/issues/276.
=> Tart isolation: use --net-softnet instead of --with-softnet

pkg/parser/parser.go
Resolves https://github.com/cirruslabs/cirrus-cli/issues/585.
=> Parser: improve unbalanced only_if: check

cmd/cirrus/main.go, go.mod, go.sum, internal/executor/instance/persistentworker/isolation/tart/cmd.go, internal/executor/instance/persistentworker/isolation/tart/tart.go, internal/executor/instance/persistentworker/isolation/tart/vm.go, internal/executor/instance/runconfig/runconfig.go, internal/worker/task.go
See https://github.com/cirruslabs/cirrus-cli/issues/587.
=> Sentry integration

internal/executor/instance/persistentworker/isolation/tart/vm.go
Make sure we run `tart stop` before the global context cancellation terminates the `tart run` process.
Should resolve most of the Sentry issues.
=> Fix graceful termination of Tart VMs

go.mod, go.sum, internal/executor/instance/persistentworker/isolation/parallels/parallels.go, internal/executor/instance/persistentworker/isolation/tart/options.go, internal/executor/instance/persistentworker/isolation/tart/tart.go, internal/executor/instance/persistentworker/persistentworker.go, internal/executor/instance/persistentworker/remoteagent/remoteagent.go, internal/worker/worker_tasks_rpc_test.go, internal/worker/worker_test.go
Resolves https://github.com/cirruslabs/cirrus-cli/issues/605.
=> Option to use a temp mounted directory for Tart isolation

internal/commands/helpers/helpers.go, internal/commands/helpers/helpers_test.go, internal/commands/run.go, internal/commands/run_test.go, pkg/larker/larker_test.go, pkg/larker/testdata/builtin-starlib/.cirrus.star
See https://github.com/cirruslabs/cirrus-cli/issues/615#issuecomment-1544777647.
=> cirrus run: introduce --env-file command-line argument

internal/worker/task.go
To help debug Tart networking issues
=> Capture to Sentry when failed to run a task

go.mod, go.sum, internal/commands/logs/output.go, internal/commands/run_test.go, internal/executor/executor.go, internal/executor/instance/container/container.go, internal/executor/instance/container/run.go, internal/executor/instance/containerbackend/containerbackend.go, internal/executor/instance/containerbackend/docker.go, internal/executor/instance/containerbackend/podman_linux.go, internal/executor/instance/containerbackend/unimplemented.go, internal/executor/instance/instance.go, internal/executor/instance/pipe.go, internal/executor/instance/prebuilt.go, internal/executor/instance/volume/volume.go, internal/executor/instance/volume/volume_test.go, internal/executor/options/container_test.go, internal/executor/pullhelper/pullhelper.go, pkg/parser/instance/container.go, pkg/parser/parseable/parseable.go, pkg/parser/parser.go, pkg/parser/parser_test.go, pkg/parser/task/task.go, pkg/parser/testdata/arm-container.json, pkg/parser/testdata/arm-container.yml
Resolves https://github.com/cirruslabs/cirrus-cli/issues/621.
=> Support arm_container instances

go.mod, go.sum, internal/evaluator/evaluator.go
Needed for https://github.com/cirruslabs/cirrus-ci-docs/issues/791.
=> EvaluateRequest: support new file system abstraction

internal/executor/instance/persistentworker/isolation/tart/tart.go, internal/executor/instance/persistentworker/isolation/tart/vm.go, internal/worker/task.go
Hopefully this will allow us to diagnose the root cause of PERSISTENT-WORKERS-12.
See also https://github.com/cirruslabs/cirrus-ci-docs/issues/1160#issuecomment-1639727838.
=> Tart executor: provide breadcrumbs

pkg/parser/node/accessor.go, pkg/parser/parser_test.go, pkg/parser/testdata/depends-on-env-list-expansion.json, pkg/parser/testdata/depends-on-env-list-expansion.yml
This way it's easier to pass lists from Starlark into YAML
=> Support YAML flow syntax after expansion

pkg/parser/parser_test.go, pkg/parser/testdata/execution-behavior-on-timeout.json, pkg/parser/testdata/execution-behavior-on-timeout.yml
See https://github.com/cirruslabs/cirrus-cli/issues/661.
=> Parser: ensure that we handle "on_timeout:" execution behavior

go.mod, go.sum, internal/executor/instance/persistentworker/isolation/tart/options.go, internal/executor/instance/persistentworker/isolation/tart/tart.go, internal/executor/instance/persistentworker/isolation/tart/vm.go, internal/executor/instance/persistentworker/isolation/vetu/options.go, internal/executor/instance/persistentworker/isolation/vetu/vetu.go, internal/executor/instance/persistentworker/isolation/vetu/vm.go, internal/executor/instance/persistentworker/persistentworker.go
See https://github.com/cirruslabs/linux-image-templates/pull/7.
=> {Tart,Vetu} isolation: support --disk-size for growing the VMs disk

internal/worker/task.go
Fixed regression introduced in #677
=> Worker: fix improper context being used for tasks

.golangci.yml, go.mod, go.sum, internal/opentelemetry/opentelemetry.go, internal/worker/task.go, internal/worker/worker.go, internal/worker/worker_test.go, internal/worker/worker_workers_rpc_test.go
=> Persistent Worker: integration test for task cancellation

internal/executor/instance/persistentworker/isolation/tart/tart.go, internal/executor/instance/persistentworker/isolation/vetu/vetu.go
Resolves https://github.com/cirruslabs/cirrus-cli/issues/685.
=> Tart and Vetu instances: introduce "prepare-instance" span

internal/worker/worker.go
=> Allow to override worker labels

PERSISTENT-WORKERS.md, internal/commands/worker/config.go, internal/executor/instance/abstract/abstract.go, internal/executor/instance/persistentworker/isolation/tart/tart.go, internal/worker/options.go, internal/worker/standby.go, internal/worker/task.go, internal/worker/worker.go, internal/worker/worker_test.go, pkg/parser/node/yaml.go
Now using the `WarmableInstance` abstraction from https://github.com/cirruslabs/cirrus-cli/pull/698.
=> Persistent Worker: support running a single standby instance

PERSISTENT-WORKERS.md, internal/commands/worker/config.go, internal/executor/executor.go, internal/executor/instance/abstract/abstract.go, internal/executor/instance/container/container.go, internal/executor/instance/persistentworker/isolation/container/container.go, internal/executor/instance/persistentworker/isolation/none/none.go, internal/executor/instance/persistentworker/isolation/parallels/parallels.go, internal/executor/instance/persistentworker/isolation/tart/options.go, internal/executor/instance/persistentworker/isolation/tart/tart.go, internal/executor/instance/persistentworker/isolation/vetu/vetu.go, internal/executor/instance/persistentworker/persistentworker.go, internal/executor/instance/pipe.go, internal/executor/instance/prebuilt.go, internal/executor/instance/unsupported.go, internal/worker/options.go, internal/worker/standby.go, internal/worker/task.go, internal/worker/worker.go, internal/worker/worker_test.go, pkg/parser/node/yaml.go
Related to #697. I think this will be simplest implementation of the functionality we want.
=> `WarmableInstance` abstraction

PERSISTENT-WORKERS.md, internal/commands/worker/config.go, internal/executor/instance/persistentworker/isolation/parallels/parallels.go, internal/executor/instance/persistentworker/isolation/tart/tart.go, internal/executor/instance/persistentworker/isolation/vetu/vetu.go, internal/executor/instance/persistentworker/remoteagent/remoteagent.go, internal/worker/options.go, internal/worker/standby.go, internal/worker/task.go, internal/worker/worker.go, internal/worker/worker_test.go
Respect resources and added tests
=> Standby improvements

go.mod, go.sum, internal/executor/instance/instance.go, internal/executor/instance/persistentworker/isolation/parallels/parallels.go, internal/executor/instance/persistentworker/isolation/tart/tart.go, internal/executor/instance/persistentworker/isolation/vetu/vetu.go, internal/executor/instance/persistentworker/persistentworker.go, internal/executor/instance/persistentworker/remoteagent/remoteagent.go, pkg/parser/instance/isolation/tart/tart.go, pkg/parser/instance/isolation/vetu/vetu.go, pkg/parser/parser_test.go, pkg/parser/testdata/cirrus.json, pkg/parser/testdata/tart-ssh-options.json, pkg/parser/testdata/tart-ssh-options.yml, pkg/parser/testdata/vetu-ssh-options.json, pkg/parser/testdata/vetu-ssh-options.yml
Resolves https://github.com/cirruslabs/cirrus-cli/issues/708.
=> Support customizing SSH port in Tart and Vetu instances

pkg/parser/instance/isolation/tart/tart.go, pkg/parser/parser_test.go, pkg/parser/testdata/cirrus.json, pkg/parser/testdata/tart-default-config.json, pkg/parser/testdata/tart-default-config.yml
So we are getting a proper StandBy configuration
=> Parse `softnet` and `display`

internal/worker/standby.go
=> Pass `parserKit` to StandBy

internal/executor/instance/persistentworker/isolation/parallels/parallels.go, internal/executor/instance/persistentworker/isolation/tart/tart.go, internal/executor/instance/persistentworker/isolation/vetu/vetu.go, internal/executor/instance/persistentworker/remoteagent/remoteagent.go
Resolves https://github.com/cirruslabs/cirrus-cli/issues/714
=> Tart: wait for SSH in bootVM

internal/executor/taskfilter/taskfilter.go
Resolves https://github.com/cirruslabs/cirrus-cli/issues/713.
=> cirrus run: match by a task's alias too, in addition to its name

internal/executor/instance/persistentworker/isolation/tart/tart.go, internal/executor/instance/persistentworker/isolation/tart/vm.go
Resolves https://github.com/cirruslabs/cirrus-cli/issues/721.
=> Tart: auto-detect the guest OS to use a proper Cirrus CI Agent binary

.cirrus.yml, PERSISTENT-WORKERS.md, internal/commands/run.go, internal/commands/run_test.go, internal/executor/instance/abstract/abstract.go, internal/executor/instance/persistentworker/isolation/vetu/vetu.go, internal/executor/instance/volume/volume_test.go, internal/executor/options/container_test.go, internal/worker/standby.go, internal/worker/worker_test.go, pkg/parser/instance/isolation/vetu/vetu.go, pkg/parser/parser_test.go, pkg/parser/testdata/cirrus.json
Resolves https://github.com/cirruslabs/cirrus-cli/issues/718.
=> Add standby instance support for Vetu

README.md
Resolves https://github.com/cirruslabs/cirrus-cli/issues/721.
=> README.md: document arm_container in the example and update Go versions

internal/agent/executor/executor.go, internal/agent/executor/shell.go, internal/agent/executor/shell_subunix_test.go, internal/agent/executor/shell_unix_test.go, internal/agent/executor/shell_windows_test.go
From https://github.com/cirruslabs/cirrus-ci-agent/pull/363 by creating a `diff` and replacing `iternal/` with `internal/agent/`
=> Cherry-picked Agent Changes

cmd/cirrus/main.go, internal/commands/helpers/exitcodeerror.go, internal/commands/internal/test/test.go, internal/commands/root.go
Resolves https://github.com/cirruslabs/cirrus-cli/issues/733.
=> cirrus internal test: allow filtering the tests using a glob expression

internal/agent/executor/cache.go
It seems we sometimes getting `getwd: no such file or directory` error for relative folders containing `**`. Not sure about the root cause but this change gracefull falls back for `CIRRUS_WORKING_DIR`.
=> Gracefully handle `getwd` errors

internal/worker/worker.go
To prevent the goroutine leak.
```
goroutine 10015 [chan receive, 52483 minutes]:
github.com/cirruslabs/echelon.(*Logger).streamEntries(0x140006b7000, {0x103d46390, 0x140007a2a20})
/go/pkg/mod/github.com/cirruslabs/echelon@v1.9.0/logger.go:74 +0x40
created by github.com/cirruslabs/echelon.NewLogger in goroutine 1
/go/pkg/mod/github.com/cirruslabs/echelon@v1.9.0/logger.go:52 +0xe4
goroutine 8 [chan receive, 55062 minutes]:
github.com/cirruslabs/echelon.(*Logger).streamEntries(0x14000052740, {0x103d46390, 0x140004801b0})
/go/pkg/mod/github.com/cirruslabs/echelon@v1.9.0/logger.go:74 +0x40
created by github.com/cirruslabs/echelon.NewLogger in goroutine 1
/go/pkg/mod/github.com/cirruslabs/echelon@v1.9.0/logger.go:52 +0xe4
goroutine 20493 [chan receive, 50209 minutes]: …
```
=> Don't instantiate a new echelon logger for each standby instance

PERSISTENT-WORKERS.md
Resolves https://github.com/cirruslabs/cirrus-cli/issues/755.
=> Document OTEL setup

pkg/parser/instance/isolation/tart/tart.go, pkg/parser/instance/isolation/vetu/vetu.go, pkg/parser/schema/schema.go, pkg/parser/testdata/cirrus.json, pkg/parser/testdata/tart-ssh-options.json, pkg/parser/testdata/tart-ssh-options.yml, pkg/parser/testdata/tart-volumes.json, pkg/parser/testdata/vetu-ssh-options.json, pkg/parser/testdata/vetu-ssh-options.yml
Resolves https://github.com/cirruslabs/cirrus-cli/issues/757.
=> Tart and Vetu instances: default to admin:admin credentials

internal/executor/instance/persistentworker/isolation/tart/vm.go
See https://github.com/cirruslabs/tart/pull/869.
=> Tart instance: pass "--no-audio" to "tart run"

PERSISTENT-WORKERS.md, internal/commands/worker/config.go, internal/executor/instance/instance.go, internal/executor/instance/persistentworker/isolation/vetu/vetu.go, internal/executor/instance/persistentworker/isolation/vetu/vm.go, internal/executor/instance/persistentworker/persistentworker.go, internal/worker/options.go, internal/worker/resourcemodifier/resourcemodifier.go, internal/worker/resourcemodifier/resourcemodifier_test.go, internal/worker/task.go, internal/worker/worker.go, internal/worker/worker_test.go, internal/worker/worker_workers_rpc_test.go
Things that are still left to be implemented:
* integration test
=> Persistent Worker: introduce resource modifiers

internal/commands/internal/test/test.go, internal/evaluator/evaluator.go, internal/executor/executor.go, internal/executor/instance/persistentworker/isolation/container/container.go, internal/executor/instance/prebuilt.go, internal/executor/instance/volume/volume_test.go
Resolves https://github.com/cirruslabs/cirrus-cli/issues/766.
=> Call container instance's Close() in container isolation's Close()

.golangci.yml, internal/executor/instance/instance.go
Resolves https://github.com/cirruslabs/cirrus-cli/issues/772.
=> Relax Docker Builder requirements on non-Windows platforms

pkg/parser/instance/isolation/container/container.go, pkg/parser/instance/isolation/isolation.go, pkg/parser/instance/isolation/parallels/parallels.go, pkg/parser/instance/proto.go, pkg/parser/instance/volume/volume.go, pkg/parser/parser_test.go, pkg/parser/testdata/proto-instance-volumes.json, pkg/parser/testdata/proto-instance-volumes.yml
Moved some files to different packages to break cycle dependency.
=> Support `volumes` field in proto instance

internal/opentelemetry/opentelemetry.go, internal/opentelemetry/opentelemetry_test.go
=> Fix OpenTelemetry schema version mismatch and add a test

internal/agent/http_cache/ghacache/ghacache.go
Otherwise we'll get HTTP 403 from S3-compatible service.
And set additional headers associated with the pre-signed request.
=> GHA cache: set Content-Length when doing S3's UploadPart

internal/agent/http_cache/azureblob/putblob.go
Some changes after testing the new GHA cache V2 protocol.
=> Azure Blob API: make sure Content-Length is set when making S3 PUT

.cirrus.yml, internal/testutil/needscontainerization.go
Also try to fix Podman tests (https://cirrus-ci.com/task/6205617104224256?logs=test#L249) in https://github.com/cirruslabs/cirrus-cli/commit/dc03397f343d64cba8cceaff609f289b49bae1cc.
=> CI: "Release" should depend on "Tests"

PERSISTENT-WORKERS.md, internal/agent/executor/executor.go, internal/agent/fallbackroundtripper/fallbackroundtripper.go, internal/agent/http_cache/azureblob/azureblob.go, internal/agent/http_cache/azureblob/getblob.go, internal/agent/http_cache/ghacache/ghacache_test.go, internal/agent/http_cache/ghacachev2/ghacachev2_test.go, internal/agent/http_cache/http_cache.go, internal/agent/http_cache/http_cache_test.go, internal/agent/http_cache/tuistcache/tuistcache_test.go, internal/commands/worker/config.go, internal/commands/worker/run.go, internal/executor/instance/abstract/abstract.go, internal/executor/instance/persistentworker/isolation/tart/options.go, internal/executor/instance/persistentworker/isolation/tart/tart.go, internal/executor/instance/persistentworker/isolation/tart/vm.go, internal/executor/instance/persistentworker/isolation/vetu/vetu.go, internal/executor/instance/persistentworker/persistentworker.go, internal/executor/instance/runconfig/runconfig.go, internal/worker/chacha/chacha.go, internal/worker/chacha/chacha_test.go, internal/worker/options.go, internal/worker/security/isolation.go, internal/worker/task.go, internal/worker/worker.go
Both for the agent and the `tart pull`.
=> Chacha integration

.goreleaser.yml, internal/executor/instance/persistentworker/isolation/tart/options.go
=> Persistent Worker: fix "softnet-allow" not being picked up

internal/agent/executor/executor.go, internal/executor/instance/persistentworker/remoteagent/remoteagent.go
Also log that Chacha transport is initialized.
=> remoteagent: support exporting of multi-line environment variables

internal/agent/executor/executor.go, internal/agent/http_cache/http_cache.go, internal/agent/http_cache/rpc_fallback.go
See https://github.com/cirruslabs/cache/pull/10.
=> Run Thunder HTTP cache in addition to the default HTTP cache

internal/agent/executor/executor.go
Explained in the comment.
Also see https://github.com/cirruslabs/chacha/pull/20.
=> Disable compression when using Chacha

internal/agent/executor/executor.go
See https://github.com/cirruslabs/chacha/pull/31.
=> Chacha transport: support direct connect functionality

go.mod, go.sum, internal/agent/fallbackroundtripper/fallbackroundtripper.go
Needed for https://github.com/cirruslabs/cirrus-cli/pull/886.
=> fallbackroundtripper: do not treat HTTP 307 as an error

go.mod, go.sum, internal/commands/localnetworkhelper/localnetworkhelper.go, internal/commands/root.go, internal/commands/run.go, internal/commands/worker/config.go, internal/commands/worker/run.go, internal/executor/executor.go, internal/executor/instance/persistentworker/isolation/parallels/parallels.go, internal/executor/instance/persistentworker/isolation/tart/tart.go, internal/executor/instance/persistentworker/isolation/vetu/vetu.go, internal/executor/instance/persistentworker/remoteagent/remoteagent.go, internal/executor/instance/runconfig/runconfig.go, internal/executor/options.go, internal/worker/options.go, internal/worker/task.go, internal/worker/worker.go
Similarly to https://github.com/cirruslabs/orchard/pull/302.
=> cirrus {run,worker run}: "Local Network" permission helper integration

internal/agent/main.go
Otherwise it's not possible to authenticate the agent using the new metadata-based transport of credentials.
=> Agent: pass org.cirruslabs.task-id, etc. metadata to streams too
