cirruslabs/cirrus-cli

README.md, internal/executor/build/task.go, internal/executor/rpc/rpc.go
Since we are not running tasks in parallel yet we can simply output logs for troubleshooting.
=> Output logs by default

.cirrus.yml, .golangci.yml, internal/executor/build/build.go, internal/executor/cache/cache.go, internal/executor/cache/cache_test.go, internal/executor/cache/putop.go, internal/executor/executor_test.go, internal/executor/rpc/cache.go, internal/executor/rpc/rpc.go, internal/executor/testdata/cache/.cirrus.yml, internal/testutil/executor.go
This implementation attempts to support parallel CLI executions and has no automatic cleaning for now.
=> Cache support

internal/executor/executor.go
Before:
```
time="2020-08-07T12:10:25+03:00" level=debug msg="cleaning up working volume ad48d026f3387e82d4e4a7e7ea6449842d0705c1b871ca8c078f40316bc44ac6"
time="2020-08-07T12:10:25+03:00" level=info msg="task test (0) new"
TestEntrypoint: executor.go:49: build failed: task test (0) new
```
After:
```
time="2020-08-07T12:11:09+03:00" level=debug msg="cleaning up working volume d120d6e535864837d0b28589451e8f367a7491a009873e476a118b4835d99f1c"
TestEntrypoint: executor.go:49: build failed: instance terminated before the task test (0) had a chance to run
```
=> Handle premature instance termination

.cirrus.yml, .golangci.yml
This helps with documenting the reasons behind disabling various linters
and fosters re-usability in other repos like [cirrus-ci-agent](https://github.com/cirruslabs/cirrus-ci-agent).
=> CI: move golangci-lint's arguments to .golangci.yml

internal/executor/rpc/noop.go
This prevents agent failures due to unimplemented RPC methods.
=> RPC: add no-op methods

internal/testutil/fs.go
Make sure to change PWD first and only then delete temp folder since Windows doesn't allow to delete current PWD.
=> Fixed order of cleanups

internal/executor/build/task.go, internal/executor/executor.go, internal/executor/rpc/rpc.go
During testing #61 I noticed CLI printed bunch of `matrix_test` tasks without labels which made it impossible to identify tasks. Let's include unique labels in an echelon scope.
=> Include unique labels in logs

internal/executor/executor.go, internal/executor/rpc/rpc.go
Previously, CLI was looking up `bridge0` instead of the `docker0` interface to find out the bridge IP on which the RPC server for the agent should run. This was essentially a typo and it worked because the fallback IP (`172.17.0.1`) returned otherwise works on default configurations.
This also adds a dynamic interface discovery via `docker network inspect bridge`, with fallback to the aforementioned `docker0` if that fails.
See #61.
=> Fix Docker bridge IP detection on Linux

.goreleaser.yml
Goreleaser can only create formulas for archives but we only publish binaries. See https://github.com/goreleaser/goreleaser/issues/1103
=> Fixed Homebrew release

internal/executor/instance/instance.go
Currently both native and RPC YAML parsers default to 2 CPUs in case nothing else is specified, and on some VMs there is only 1 CPU.
Do our best effort and try to run the task anyway, since the user has already signified his intent to do so.
=> Clamp CPU and memory to resources available for Docker daemon

go.mod, internal/commands/validate.go, internal/testutil/api.go, pkg/parser/boolevator/boolevator.go, pkg/parser/instance/additionalcontainer.go, pkg/parser/instance/container.go, pkg/parser/node/accessor.go, pkg/parser/node/accessor_test.go, pkg/parser/parseable/parseable.go, pkg/parser/parser.go, pkg/parser/parser_test.go, pkg/parser/task/behavior.go, pkg/parser/task/default.go, pkg/parser/task/handler.go, pkg/parser/task/pipe.go, pkg/parser/task/task.go, pkg/parser/testdata/example-android.json, pkg/parser/testdata/example-flutter-web.json, pkg/parser/testdata/example-mysql.json, pkg/parser/testdata/example-rust.json
This makes sure that we compare the actual parsing results (and not merely check the absence of errors) with the expected fixture contents.
`cirrus validate --json` can be used to generate the fixtures.
=> Parser JSON tests

internal/commands/run.go, internal/commands/run_test.go, internal/commands/testdata/docker-no-pull/.cirrus.yml, internal/executor/build/build.go, internal/executor/executor.go, internal/executor/instance/instance.go, internal/executor/options.go, internal/executor/options/docker.go, internal/executor/options/docker_test.go
This brings back the old behavior where we always attempted to pull the latest container image before starting, but lets the user turn it off in case they want to run CI tasks with locally-built container images.
Always pulling images also avoids some tricky-to-diagnose cases like in cirruslabs/cirrus-ci-annotations#22, where running two similar configurations resulted in different results due to stale state in the Docker daemon.
=> Introduce run's --docker-no-pull argument

.goreleaser.yml
[prerelease](https://goreleaser.com/customization/release/) and [skip_upload](https://goreleaser.com/customization/homebrew/) set to "auto" ensure that we don't mark release candidates as releases and don't upload their formulas.
=> .goreleaser.yml: treat release candidates accordingly

internal/commands/run_test.go
After #82 the -v flag no longer enables the simple mode. Enable it again.
=> Fix running tests locally by enabling simple mode

.goreleaser.yml, cmd/cirrus/main.go, go.mod, go.sum, internal/commands/root.go
Make sure the `--version` is always present and adheres to the `version-commit` format.
This also ensures that version of the `cirrus` installed via `go get` is consistent with the binary builds versions (currently it's `v0.7.0` vs `0.7.0`).
See #73.
=> Consistent version format

internal/executor/testdata/additional-containers/.cirrus.yml
Turns out that MySQL is simply taking too long to start up (initializing InnoDB storages) when running multiple tests in parallel and we need to wait a little longer than 60 seconds mandated by the agent.
=> TestAdditionalContainers: fix flakiness by using wait-for-it

go.mod, go.sum, internal/commands/run_test.go, internal/executor/build/task.go, internal/executor/executor.go, internal/executor/rpc/rpc.go
There is a problem sometimes to distinguish task's output from an instruction output in dumb terminal mode.
```yaml
test_task:
test_script: ./.ci/test.sh
```
The above config will produce a bit confusing output with two identical "Started 'test'". This change will fix it by making tasks scopes more descriptive.
=> Unique task description

pkg/larker/loader/git/git.go
This fixes the `TestLoadGitHelpers` test which otherwise fails because it requires a module from the revision excluded by the depth limit.
=> Remove depth limit when fetching Starlark modules from Git

pkg/larker/builtin/fs.go, pkg/larker/fs/dummy/dummy.go, pkg/larker/fs/fs.go, pkg/larker/fs/github/github.go, pkg/larker/fs/github/github_test.go, pkg/larker/fs/local/local.go, pkg/larker/fs/local/local_test.go, pkg/larker/larker_test.go, pkg/larker/loader/loader.go, pkg/larker/testdata/builtin-fs/.cirrus.star, pkg/larker/testdata/builtin-fs/read-some-file.txt
See #53.
Example use-case:
```python
load("cirrus", "fs")
def main(ctx):
tasks = base_tasks()
if fs.exists(".goreleaser.yml"):
tasks += goreleaser_tasks()
return tasks
```
What I don't particularly like at the moment is how we handle the lack of exceptions, e.g. `fs.readdir()` on a non-directory will result in non-recoverable error. The question is: is it actually that bad as it sounds?
=> Starlark filesystem builtins

go.mod, go.sum, pkg/larker/larker.go, pkg/larker/larker_test.go, pkg/larker/loader/loader.go, pkg/larker/options.go, pkg/larker/testdata/builtin-env/.cirrus.star, pkg/larker/testdata/builtin-starlib/.cirrus.star
=> cirrus module: exposed some Starlib builtins and added an env dict

internal/executor/instance/instance.go
Some container images (e.g. `mysql` and `postgres`) define anonymous volumes [in their specification](https://docs.docker.com/engine/reference/builder/#volume).
These volumes keep lingering even after we remove the container itself, however, there's a quick fix for that.
=> When removing containers remove their anonymous volumes too

internal/commands/run.go, internal/commands/run_test.go, internal/commands/testdata/run-environment-starlark/.cirrus.star, internal/executor/environment/environment.go, internal/executor/executor.go, internal/executor/options.go
Also inject project-specific environment variables into the executor, which was not done previously for some reason.
=> Share executor's base and user environment variables with Starlark

pkg/parser/instance/additionalcontainer.go, pkg/parser/instance/container.go, pkg/parser/instance/proto.go, pkg/parser/instance/resources.go, pkg/parser/instance/resources_test.go, pkg/parser/node/accessor.go, pkg/parser/options.go, pkg/parser/parser.go, pkg/parser/parser_test.go, pkg/parser/task/command.go, pkg/parser/task/handler.go, pkg/parser/task/pipe.go, pkg/parser/task/task.go, pkg/parser/testdata/proto-instance.json, pkg/parser/testdata/proto-instance.yml
This an implementation of a parser that can take a type descriptor (basically a serializable definition) and parse it back into a proto message. This is need for the future of the CLI when it will be able to act a service for evaluating of the YAML and Starlark configs for the Cirrus Cloud. `EvaluateConfigRequest` will need to be modified: `AdditionalInstancesInfo` will be added.
```protobuf
message EvaluateConfigRequest {
message AdditionalInstancesInfo {
map<string, string> instances = 1; // field name to proto FQN
google.protobuf.FileDescriptorSet descriptor = 2;
}
string yaml_config = 1;
string starlark_config = 2;
map<string, string> environment = 3;
repeated string affected_files = 4;
map<string, string> files_contents = 5;
AdditionalInstancesInfo additional_instances_info = 6;
} …
```
=> Generic Proto Instance Parser

internal/commands/root.go, internal/commands/run.go, internal/commands/serve.go, internal/evaluator/evaluator.go, internal/evaluator/evaluator_test.go, pkg/larker/fs/memory/memory.go, pkg/parser/options.go, pkg/parser/parser.go, pkg/parser/parser_test.go
=> Introduce serve command

STARLARK.md, go.mod, go.sum, internal/commands/internal/test.go, pkg/larker/fs/local/local.go, pkg/larker/fs/local/local_test.go
No need do document security pitfalls if we can avoid them.
=> Prevent local filesystem traversal

pkg/parser/parser.go
This should fix failing tests on 92823bc07bc0fd18330155d9a4522eeeac00b09e.
=> Sort tasks by their IDs to make output consistent across runs

Dockerfile, cloudbuild.yaml
Config is similar to the agent repository.
Let's add an additional docker image location in gcr.io for easier integration with GCP service like Cloud Run.
=> Explicit Cloud Build Config

README.md, internal/executor/instance/instance.go, internal/executor/instance/volume.go
Unfortunately, taking the least-privilege path by running the container with the current users context (using `--security-opt="label=user:USER"`) and other labels doesn't work, because the container filesystem seems to be already labeled with the container-specific labels, which prevents us from even running the entrypoint binary.
See #124.
=> Disable SELinux for service container and --dirty containers

README.md, internal/executor/heuristic/heuristic.go, internal/executor/instance/instance.go, internal/executor/rpc/rpc.go
This approach somewhat simplifies the communication with the agent on Linux by making the Docker bridge heuristic obsolete and resolves the #124 by essentially bypassing the Netfilter altogether.
Unfortunately, Cloud Build heuristic had to be kept in place, because in Cloud Build the CLI runs inside a container (as a part of the build step), but when asking the Docker daemon to bind-mount something we need to pass a path accessible on the host, not inside the container.
Also, SELinux confinement had to be disabled even when not using `--dirty` mode because using Docker's [`:z` relabelling feature](https://docs.docker.com/storage/bind-mounts/#configure-the-selinux-label) on Unix domain sockets doesn't seem to work the same way it works on files: the label of the process that listens the …
=> Use Unix socket to communicate with the agent on Linux

.goreleaser.yml, internal/commands/helpers/helpers.go, internal/commands/internal/internal.go, internal/commands/internal/test/test.go, internal/commands/internal/test/test_unsupported.go, internal/commands/root.go, internal/commands/run.go, internal/commands/run_unsupported.go, internal/commands/serve.go, internal/commands/serve_unsupported.go, internal/commands/worker/worker.go, internal/executor/heuristic/common.go, internal/executor/heuristic/heuristic.go, internal/executor/heuristic/heuristic_unsupported.go, internal/executor/instance/containerbackend/docker.go, internal/executor/instance/containerbackend/docker_unsupported.go
Sync operating systems and architectures with the cirrus-ci-agent's [`.goreleaser.yml`](https://github.com/cirruslabs/cirrus-ci-agent/blob/master/.goreleaser.yml).
Resolves #149.
=> Build for more platforms

internal/executor/instance/containerbackend/docker.go
Fixes the CLI's container backend auto-detection mode by not returning an unusable Docker client to the caller.
=> Ensure that the Docker client is working before returning it

go.mod, go.sum, internal/evaluator/evaluator.go, internal/evaluator/evaluator_test.go, internal/executor/instance/instance.go, pkg/parser/instance/container.go, pkg/parser/instance/proto.go, pkg/parser/labels.go, pkg/parser/parser.go, pkg/parser/schema/schema.go, pkg/parser/task/task.go, pkg/parser/testdata/via-rpc/container_build-arguments.json, pkg/parser/testdata/via-rpc/container_build-complexArguments.json, pkg/parser/testdata/via-rpc/container_build-context.json, pkg/parser/testdata/via-rpc/container_build-simple.json, pkg/parser/testdata/via-rpc/container_build-twoTasksSameContainer.json, pkg/parser/testdata/via-rpc/environment-complex4.json, pkg/parser/testdata/via-rpc/matrix-puppeteer.json
No more `schema.TodoSchema`.
However, the descriptions for the messages and fields used in the dynamic instances are currently empty. Once we figure out the best way to add descriptions, I'll add a synthetic test to validate dynamic instance schema generation.
=> JSONSchema() RPC method + dynamic instance support when generating schema

internal/executor/rpc/rpc.go
It appeared to always be the root logger 🤦‍♂️
=> Fixed logger scope

internal/executor/executor_test.go, internal/executor/rpc/rpc.go, internal/executor/testdata/logging-no-extra-newlines/.cirrus.yml
=> When printing logs from RPC don’t print an extraneous newline

pkg/larker/larker.go, pkg/larker/larker_test.go, pkg/larker/testdata/no-tasks/.cirrus.star
For some reason `yaml.Marshal` of an empty map resulted in `{}` instead of an empty string.
=> Fixed generation of empty list

.cirrus.yml
See https://github.com/golang/go/issues/42684.
=> No need to explicitly codesign darwin/arm64 binary

README.md
It makes more sense since there's more CLI-specific information there, and the original Docker/Podman links too.
=> Route README.md's Docker and Podman links to INSTALL.md

internal/executor/instance/containerbackend/podman_linux.go
This results in `podman inspect` output similar to one can get when running with `--security-opt label=disable`.
However, for some reason the container process gets a label like `system_u:system_r:container_t:s0:c283,c879` instead of `unconfined_u:system_r:spc_t:s0`.
Resolves #192.
=> Podman backend: properly treat SELinux disable flag

pkg/parser/instance/windowscontainer.go, pkg/parser/parser.go, pkg/parser/parser_test.go, pkg/parser/task/task.go, pkg/parser/testdata/via-rpc/container_build-osVersion.json, pkg/parser/testdata/via-rpc/container_build-osVersion.yml
Needed to run with `--experimental-parser` on Windows when using Windows Containers introduced in #188.
=> windows_container instance support in parser

pkg/parser/parser.go
=> Allocate task's local index ID before only_if filtration

internal/executor/instance/persistentworker/isolation/parallels/vm.go
This way it will be easier to distribute VMs and do upgrades. For an upgrade one will just need to download a new VM as a single file and then delete the previous VM folder and register the packed VM.
FYI @edigaryev
=> Support Packed Parallels VMs

pkg/parser/instance/container.go, pkg/parser/instance/proto.go, pkg/parser/instance/windowscontainer.go, pkg/parser/node/accessor.go, pkg/parser/node/accessor_test.go, pkg/parser/parser_test.go, pkg/parser/testdata/docker-arguments-env.json, pkg/parser/testdata/docker-arguments-env.yml
Related to https://github.com/cirruslabs/cirrus-ci-docs/issues/692
=> Expand mapping values with environment variables

pkg/parser/parser.go, pkg/parser/task/dockerbuilder.go, pkg/parser/task/pipe.go, pkg/parser/task/task.go, pkg/parser/task/tasklike.go, pkg/parser/testdata/via-rpc/new-alias-reuse.json, pkg/parser/testdata/via-rpc/new-alias-reuse.yml, pkg/parser/testdata/via-rpc/new-duplicate-task-names-are-kept.json, pkg/parser/testdata/via-rpc/new-duplicate-task-names-are-kept.yml
They are not a substitute for names.
=> Parser: properly treat task aliases

pkg/parser/node/finder.go, pkg/parser/node/node.go, pkg/parser/testdata/via-rpc/new-virtual-node-is-deepcopied.json, pkg/parser/testdata/via-rpc/new-virtual-node-is-deepcopied.yml
This fixes a regression introduced in https://github.com/cirruslabs/cirrus-cli/pull/209.
=> Parser: properly deep-copy the virtual node used for collectible fields

pkg/parser/node/finder.go
Fixes regression after #224 when a collectible field of a collectible filed stopped properly parse from top level.
=> Link virtual node back to tree

go.mod, go.sum, internal/evaluator/evaluator.go, pkg/parser/parser.go, pkg/parser/parser_test.go, pkg/parser/testdata/tasks-count-before-filtering.yml
Support the helper field to aid in remote use of the Go parser.
=> Evaluator: populate tasks_count_before_filtering field

pkg/parser/boolevator/operator.go, pkg/parser/boolevator/operator_test.go, pkg/parser/testdata/via-rpc/new-only-if-with-nonexistent-env-var.json, pkg/parser/testdata/via-rpc/new-only-if-with-nonexistent-env-var.yml
Otherwise the boolevator will give false-positives for non-existent environment variables that are expanded to `""`.
=> Boolevator: ensure we match the whole string

internal/executor/instance/persistentworker/isolation/parallels/parallels.go
The defaults were 10 attempts with 100ms delays
=> Less strict retry options for IP retrival

internal/executor/instance/persistentworker/isolation/parallels/parallels.go, pkg/parser/labels.go, pkg/parser/parser_test.go, pkg/parser/testdata/additional-instance-stability.json, pkg/parser/testdata/additional-instance-stability.yml
This ensures that things like osx_instance and macos_instance won't get randomized, resulting in incorrect unique labels set.
Also fix a linter error that somehow made it to the master.
=> Parser: provide stable iteration order for additional instances

internal/executor/instance/persistentworker/isolation/parallels/parallels.go
Suspended VMs don't pick time right away
=> [worker] force time sync for Parallels VMs

internal/commands/run.go, internal/commands/validate/validate.go, internal/executor/executor_test.go, internal/testutil/executor.go, pkg/rpcparser/parser_test.go
The old parser can be enabled with `--experimental-old-parser`.
Resolves #251.
=> Use built-in Go parser by default

internal/commands/run.go, internal/commands/validate/validate.go, internal/executor/executor_test.go, internal/testutil/executor.go, pkg/rpcparser/parser_test.go
There are still some issues with the `gopkg.in/yaml.v2` left.
=> Temporarily switch back to remote parser

.cirrus.yml, internal/commands/logs/foldable.go, internal/executor/cache/cache_test.go, pkg/parser/instance/isolation/isolation.go, pkg/parser/instance/isolation/parallels.go, pkg/parser/instance/persistentworker.go, pkg/parser/parser_test.go, pkg/parser/task/task.go, pkg/parser/testdata/cirrus.json, pkg/parser/testdata/via-rpc/new-persistentworker-isolation-none.json, pkg/parser/testdata/via-rpc/new-persistentworker-isolation-none.yml, pkg/parser/testdata/via-rpc/new-persistentworker-isolation-parallels.json, pkg/parser/testdata/via-rpc/new-persistentworker-isolation-parallels.yml
The tests will pass (with a little nudge) once corresponding changes to the cloud parser will be rolled out.
Resolves #252.
=> Parser: support persistent_worker isolation

internal/executor/instance/persistentworker/isolation/parallels/parallels.go, internal/executor/instance/persistentworker/isolation/parallels/parallels_test.go
This should improve the robustness in the presence of network errors, but this makes an assumption that time is synchronized properly on the host.
The time format passed to the `date` command is [governed by POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/date.html), so it should work on all other platforms (see #253), except for the Windows.
Should help with cirruslabs/cirrus-ci-docs#772.
=> Parallels: sync time without NTP

.cirrus.yml
Should help with Podman installation failing.
=> Use GWDG's mirror instead of broken openSUSE traffic director

go.mod, go.sum, pkg/parser/modifier/matrix/matrix_test.go, pkg/parser/node/accessor_test.go, pkg/parser/node/finder_test.go, pkg/parser/node/matrix.go, pkg/parser/node/matrix_test.go, pkg/parser/node/node.go, pkg/parser/node/node_test.go, pkg/parser/node/yaml.go, pkg/parser/parser.go, pkg/parser/parser_test.go, pkg/parser/testdata/via-rpc/new-floats-are-picked-up-as-is.json, pkg/parser/testdata/via-rpc/new-floats-are-picked-up-as-is.yml, pkg/parser/testdata/via-rpc/new-non-standard-list-merging.json, pkg/parser/testdata/via-rpc/new-non-standard-list-merging.yml
This improves Go parser compatibility with the Cloud parser, mainly:
* floats and other non-trivial types are treated as is (see `new-floats-are-picked-up-as-is.yml`)
* non-standard alias merging of lists when using `<<` map keys (see `new-non-standard-list-merging.yml`)
As a side-effect we can now easily save the line and a column from `yaml.Node` in `node.Node` and emit more useful parser error messages.
=> Parser: switch to yaml.v3

go.mod, go.sum, pkg/parser/bfunc.go, pkg/parser/bfunc_test.go
This improves compatibility with the Cloud Parser and fixes some cases found in the wild.
=> Parser: use cirruslabs/go-java-glob for changesInclude function

.golangci.yml
=> .golangci.yml: sort out previously disabled linters

go.mod, go.sum, internal/executor/instance/persistentworker/isolation/parallels/vm.go, internal/executor/instance/persistentworker/isolation/parallels/vmkiller.go, internal/executor/instance/persistentworker/isolation/parallels/vmkiller_darwin.go, internal/executor/instance/persistentworker/isolation/parallels/vmkiller_unsupported.go
Should help with the problems observed in #248.
=> Parallels: kill prl_vm_app processes before running new VMs

internal/commands/run.go, internal/commands/validate/validate.go, pkg/parser/parsererror/parsererror.go, pkg/parser/parsererror/parsererror_test.go
Looks like this:
```
% ~/cirrus run --experimental-parser 
3:     image: debian:latest
4: 
5:   script: echo "I'm a first task!"
6: 
7: second_task:
8:   containers:
^
9: 
10:   script: true
11: 
12: third_task:
13:   container:
Error: parsing error: 8:3: task has no instance attached
2021/02/08 21:53:58 parsing error: 8:3: task has no instance attached
```
=> cirrus {run,validate}: provide context lines for *parsererror.Rich

internal/executor/instance/persistentworker/isolation/parallels/parallels.go
Otherwise we might get a context cancelled error and still do the retries until the default 10 attempt counter reaches zero.
=> Parallels: only retry on specific errors

internal/executor/instance/persistentworker/isolation/parallels/cli.go, internal/executor/instance/persistentworker/isolation/parallels/cli_test.go, internal/executor/instance/persistentworker/isolation/parallels/clone.go, internal/executor/instance/persistentworker/isolation/parallels/server.go, internal/executor/instance/persistentworker/isolation/parallels/vm.go
This also fixes `stdout` reuse error in `VM.Close()`:
https://github.com/cirruslabs/cirrus-cli/blob/680cf039a36de18524e5c5a9028d352f7785ed48/internal/executor/instance/persistentworker/isolation/parallels/vm.go#L141-L145
=> Parallels: fix and simplify Prlctl/Prlsrvctl handling

internal/executor/platform/platform.go
To include https://github.com/cirruslabs/cirrus-ci-agent/pull/98 fix.
=> Bump agent's version

.cirrus.yml, internal/executor/agent/agent.go, internal/executor/executor_darwin_test.go, internal/executor/instance/persistentworker/isolation/parallels/cli_test.go, internal/executor/instance/persistentworker/isolation/parallels/clone.go, internal/executor/instance/persistentworker/isolation/parallels/parallels.go, internal/executor/instance/persistentworker/isolation/parallels/vm.go, internal/executor/instance/persistentworker/persistentworker.go, internal/worker/worker_test.go
As for the Windows, we could use [github.com/masterzen/winrm](https://github.com/masterzen/winrm) + [github.com/packer-community/winrmcp](https://github.com/packer-community/winrmcp) (a nasty Powershell abomination for copying files), but this requires the user to pre-configure the WinRM in the base image and it's unclear how we are going to test this.
So my proposal here is to simply skip the Windows use-case in favor of the Cirrus Cloud since no-one asked for it.
Resolves #253.
=> Parallels: support Linux as a target platform

internal/commands/run.go
=> cirrus run: hide --debug-no-cleanup flag

.cirrus.yml
Go 1.16 was just released and GoReleaser introduced darwin/arm64 support [a few hours ago](https://github.com/goreleaser/goreleaser/releases/tag/v0.156.0).
=> No need for gotip anymore

.cirrus.yml
Resolved by upstream in https://github.com/containers/podman/issues/9390#issuecomment-780108627.
=> Podman: remove missing search registries workaround

.golangci.yml, internal/executor/instance/container.go, internal/executor/instance/persistentworker/isolation/none/none.go, internal/worker/worker_tasks_rpc_test.go, pkg/parser/instance/isolation/isolation.go, pkg/parser/instance/isolation/parallels.go, pkg/parser/parseable/parseable.go, pkg/parser/task/behavior.go, pkg/parser/task/piperesources.go
Blacklist is still kept to enable new linter recommendations in the future.
=> .golangci.yml: use linter whitelist instead of blacklist

internal/evaluator/evaluator_test.go, pkg/parser/instance/proto.go, pkg/parser/task/task.go
If proto instance like `persistent_worker` doesn't have `platform` field then don't assume it's `linux` and simply don't set `CIRRUS_OS`.
=> Don't assume platform by default

pkg/parser/parseable/default.go, pkg/parser/parseable/parseable.go, pkg/parser/parser_test.go, pkg/parser/task/task.go, pkg/parser/testdata/via-rpc/new-collectible-property-deprioritize.json, pkg/parser/testdata/via-rpc/new-collectible-property-deprioritize.yml, pkg/parser/testdata/via-rpc/new-collectible-property-instances-are-evaluated-at-the-end.json, pkg/parser/testdata/via-rpc/new-collectible-property-instances-are-evaluated-at-the-end.yml, pkg/parser/testdata/via-rpc/new-collectible-property-overwritten-by-the-user.json, pkg/parser/testdata/via-rpc/new-collectible-property-overwritten-by-the-user.yml
They're now ranked by their position in the node (if any) and whether they define an instance or not.
=> Parser: fix collectible fields evaluation order

pkg/parser/node/node.go
Otherwise their lines and columns are left as default values (0 and 0).
=> Parser: update line and column when merging into virtual nodes

pkg/parser/labels.go
When additional instances were in use their labels were not filtered due to an early exit from `instanceLabels()`.
Follow-up to #325.
=> Parser: properly filter out empty instance labels

go.mod, go.sum, internal/commands/helpers/helpers.go, internal/commands/internal/test/test.go, internal/evaluator/evaluator.go, internal/evaluator/evaluator_test.go, pkg/larker/larker.go, pkg/larker/larker_test.go
`github.com/cirruslabs/cirrus-ci-agent`'s version can be changed to a proper one after https://github.com/cirruslabs/cirrus-ci-agent/pull/111 gets merged.
=> Evaluator: send output_logs

pkg/parser/boolevator/boolevator.go, pkg/parser/boolevator/boolevator_test.go
`strings.Trim` removes all leading or trailing character so string like `"foo 'foo'"` will get both `'` and `"` trimmed from the end.
=> [boolevator] properly unquote string literal

internal/executor/instance/abstract/abstract.go, internal/executor/instance/container.go, internal/executor/instance/persistentworker/isolation/none/none.go, internal/executor/instance/persistentworker/isolation/parallels/parallels.go, internal/executor/instance/pipe.go, internal/executor/instance/prebuilt.go, internal/executor/platform/platform.go, internal/worker/task.go, internal/worker/worker.go
The build will start to pass once https://github.com/cirruslabs/cirrus-ci-agent/pull/120 is merged and released as `1.38.0`.
Resolves #352.
=> Persistent worker: clean-up working directory used by the agent

internal/executor/instance/persistentworker/isolation/none/none.go
To improve caching, see https://github.com/cirruslabs/cirrus-cli/issues/357#issuecomment-814250111.
=> Persistent worker: prefer static temporary directory over dynamic one when possible

internal/evaluator/evaluator.go, internal/executor/executor_darwin_test.go, pkg/larker/larker.go
* it's OK to have a Starlark configuration with no `main()` defined — a common use-case for this is using hooks
* use a separate gRPC error code to differentiate between cases when:
* hook wasn't defined
* all other cases (e.g. hook failed to execute or wasn't a function)
=> Evaluator: properly treat cases where entrypoint is not found

go.mod, go.sum, internal/evaluator/evaluator.go, internal/evaluator/evaluator_test.go, pkg/parser/parser.go, pkg/parser/parser_test.go, pkg/parser/testdata/problematic-potentially-missed-task.yml
And also route these warnings through an evaluator.
Resolves #329.
=> Parser: emit warnings on tasks named task_*

Dockerfile
This flag was introduced recently in https://github.com/goreleaser/goreleaser/pull/2179.
=> Speed-up image build by using goreleaser's --single-target

pkg/larker/converthook.go
So that we don't have to do things like `int(ctx.payload.data.build.id)`.
=> Larker: opportunistically convert incoming float values to integers

internal/executor/instance/persistentworker/isolation/parallels/parallels.go, internal/worker/task.go
And don't treat the context cancellation in persistent worker as an error.
Resolves #373.
=> Parallels: check if the context was cancelled before handling the actual sess.Wait()'s error

pkg/larker/loader/loader.go
With certificates installed
Seems right now `http` module fails to execute requests because of that. I'm seeing 
> INVALID_ARGUMENT: exec failed: Get "https://httpbin.org/json": dial tcp 34.231.30.52:443: i/o timeout!
on 
```python
load("cirrus", "http")
def main(ctx):
resp = http.get("https://httpbin.org/json")
if resp.status_code != 200 or resp.json().get("slideshow") == None:
fail("failed to parse JSON")
print(resp)
return []
```
=> Use custom HTTP client in Starlark

.cirrus.star, pkg/larker/larker_test.go, pkg/larker/loader/git/git.go, pkg/larker/loader/git/git_test.go
All the new repos has `main` as the default branch. Since the feature is not announced and all the Cirrus Templates will be created with the new defaults it's reasonable to change it here too.
=> Use main as the default revision

STARLARK.md, internal/commands/internal/test/test.go, pkg/larker/larker.go, pkg/larker/larker_test.go, pkg/larker/loader/loader.go, pkg/larker/options.go, pkg/larker/testdata/test-mode/.cirrus.star
To simplify writing complex tests.
Related to #354 and #381.
=> Starlark: new is_test cirrus builtin

.golangci.yml, pkg/larker/larker.go, pkg/larker/larker_test.go, pkg/larker/testdata/main-returns-dict/.cirrus.star, pkg/larker/testdata/main-returns-dict/expected.yaml
Note that it's not possible to [construct a dictonary with duplicate keys](https://docs.bazel.build/versions/2.1.0/skylark/lib/dict.html) in Starlark, so this approach is somewhat limited and forces the user to name the tasks differently, and not just `task:`
Resolves https://github.com/cirruslabs/cirrus-cli/issues/398.
=> Starlark's main(): allow returning dict in addition to list

go.mod, go.sum, pkg/parser/instance/additionalcontainer.go, pkg/parser/testdata/cirrus.json, pkg/parser/testdata/via-rpc/simple-additionalContainers.json, pkg/parser/testdata/via-rpc/simple-additionalContainers.yml
The command should be a string which is tokenized like `CMD` in a Dockerfile.
=> Fixed parsing of command for additional containers

internal/commands/validate/validate.go, internal/commands/validate_test.go
Hi guys, thank you very much again for the awesome tools. I am really excited with the new Starlak builds.
With this PR I propose adding adding a `--print` flag to the `validate` command of Cirrus CLI. This idea is to allow users to inspect what they are creating in Starlak (some small quality of life improvement). What do you think about this idea?
I am not very experience with Go, but I gave it a try, hopefully I didn't do anything wrong.
I did manage to run `go test -v internal/commands/validate_test.go` and check the unit test I have added, but I am still trying to find a way of compiling the project locally into a single file executable...
=> Add --print option to validate

internal/evaluator/evaluator.go, pkg/larker/fs/failing/failing.go
To prevent things like https://github.com/cirruslabs/cirrus-cli/issues/442 in the future.
=> Evaluator: fail when cirrus.fs is used but no GitHub FS was initialized

internal/commands/validate_test.go, pkg/larker/convertmain.go, pkg/larker/larker.go, pkg/larker/larker_test.go, pkg/larker/testdata/main-returns-list/.cirrus.star, pkg/larker/testdata/main-returns-list/expected.yaml, pkg/larker/testdata/main-returns-tuple-list/.cirrus.star, pkg/larker/testdata/main-returns-tuple-list/expected.yaml, pkg/larker/testdata/mixed-list/.cirrus.star, pkg/larker/testdata/mixed-list/expected.yaml, pkg/parser/parser_test.go
Cirrus interpretation of the YAML file allows repeated keys.
While standard YAML (that forbids repeated keys) maps very nicely to Starlak, this feature cannot be achieved if users are constrained to return either a dict or a list of task (dict) objects.
This PR proposes allowing a list of tuples `[(key, value)]` as an equivalent to returning a dict from `main` in a Starlark script, to circumvent this limitation.
*Motivation*: until recently, Cirrus web interface was displaying warning for some scenarios where repetition was not being used (https://github.com/cirruslabs/cirrus-ci-docs/issues/887). I also don't know if some instructions can be prefixed (e.g. `docker_builder`, it is not clear on the [docs](https://cirrus-ci.org/guide/docker-builder-vm/))
Returning dicts (or equivalent) is …
=> Allow starlark main to return a list of tuples

pkg/parser/parser.go, pkg/parser/parser_test.go, pkg/parser/task/dockerbuilder.go, pkg/parser/task/pipe.go, pkg/parser/task/task.go, pkg/parser/task/tasklike.go, pkg/parser/testdata/invalid-multiple-name-ambiguity.yml, pkg/parser/testdata/issues/multiple-name-ambiguity.yml, pkg/parser/testdata/issues/no-multiple-name-ambiguity.yml
This effectively reverts the https://github.com/cirruslabs/cirrus-cli/pull/429 and resolves https://github.com/cirruslabs/cirrus-cli/issues/444 and also resolves https://github.com/cirruslabs/cirrus-ci-docs/issues/887.
Instead of emitting a warning on each override instance (as it turns out overriding names can be useful, see https://github.com/cirruslabs/cirrus-ci-docs/issues/887), emit a more helpful dependency error in cases described https://github.com/cirruslabs/cirrus-cli/issues/427.
=> Parser: more helpful error message for overridden task names dependents

pkg/larker/fs/github/github.go, pkg/larker/fs/github/github_test.go
An alternative implementation of https://github.com/cirruslabs/cirrus-cli/pull/473 that also caches information about directories.
=> GitHub FS: fileInfos cache

internal/evaluator/evaluator.go, pkg/larker/fs/git/git.go, pkg/larker/fs/git/git_test.go, pkg/larker/fs/github/github.go, pkg/larker/fs/github/github_test.go, pkg/larker/fs/githubfixture/githubfixture.go, pkg/larker/loader/module_fs.go
Also there's now a helper package named `githubfixture` that can be used to test various FS implementations that can access GitHub repositories against it.
=> Move GitHub FS back to it's package and fix last linter error

.cirrus.yml, internal/executor/testdata/resource-limits/.cirrus.yml
Since now we have an M1 one without Parallels installed
=> More specific persistent worker

PERSISTENT-WORKERS.md
...and a way to run with `sudo`.
See https://github.com/cirruslabs/cirrus-cli/pull/483.
=> Document default persistent worker privileges

.cirrus.yml, internal/executor/instance/volume/volume.go, pkg/parser/modifier/merger/merger.go, pkg/parser/node/matrix.go, pkg/parser/node/node.go, pkg/parser/node/yaml_test.go, pkg/parser/parser.go, pkg/parser/parser_test.go, pkg/parser/testdata/yaml-scripts-merging.json, pkg/parser/testdata/yaml-scripts-merging.yml
This one focuses only on aliases, because merging everything per YAML spec is not easy as it sounds at this moment:
* we have to exclude `always`, `on_failure`, `upload_caches` and possibly others
* we have to support old behavior where duplicate key contents are merged together, e.g.: https://github.com/cirruslabs/cirrus-cli/blob/9f9dfcda39cbbd9ac260c1a30c3023a1c3111ea5/pkg/parser/testdata/via-rpc/new-deduplicator-same-type.yml#L6-L12
Resolves https://github.com/cirruslabs/cirrus-ci-docs/issues/980.
=> Parser: fix map merging when using aliases

internal/commands/worker/run.go
The fix is primarily for the integration tests.
Previously the command-line argument was propagated:
https://github.com/cirruslabs/cirrus-cli/blob/2946d2a8301056ea5bb3fca6bd1c3e0f74e54af3/internal/worker/task.go#L53
But now it's not due to `endpoint.Endpoint` revamp.
=> Persistent Worker: fix RPC endpoint configuration when ran via CLI

go.mod, go.sum, internal/executor/instance/persistentworker/isolation/tart/tart.go, internal/executor/instance/persistentworker/isolation/tart/vm.go, internal/executor/instance/persistentworker/persistentworker.go, internal/worker/worker_test.go, pkg/parser/instance/isolation/tart.go, pkg/parser/testdata/cirrus.json, pkg/parser/testdata/via-rpc/new-persistentworker-isolation-tart.json, pkg/parser/testdata/via-rpc/new-persistentworker-isolation-tart.yml
Tart tests will pass once a new `tart` binary will be deployed to a test machine.
Resolves https://github.com/cirruslabs/cirrus-cli/issues/496.
=> Support configurable CPU/Memory for Tart isolation

pkg/parser/node/matrix.go, pkg/parser/node/yaml.go, pkg/parser/parseable/parseable.go, pkg/parser/parser.go, pkg/parser/parser_test.go, pkg/parser/testdata/yaml-merge-collectible.json, pkg/parser/testdata/yaml-merge-collectible.yml
The issue is as follows, let's say we have the following Cirrus CI configuration:
```YAML
container:
image: debian:latest
first: &first
env:
FIRST: first
second: &second
env:
SECOND: second
task:
<<: *first
<<: *second
```
Per YAML spec (https://yaml.org/type/merge.html), the result should be:
```yaml
container:
image: debian:latest
task:
env:
FIRST: first
```
However, that's not how Cirrus Cloud parser worked before. It worked like this:
```yaml
container:
image: debian:latest
task:
env:
FIRST: first
SECOND: second
```
However, if we were to stop following the YAML spec, things like this wouldn't work correctly:
```yaml
container:
image: debian:latest
.task_template: &task-template
install_tools_script:
- apt-get install screen
install_tmux_task:
install_tools_script:
- apt-get install …
```
=> Parser: implement merge exemptions to work around YAML merging issue

internal/commands/run.go, internal/executor/executor.go, internal/executor/instance/persistentworker/isolation/tart/tart.go, internal/executor/instance/persistentworker/isolation/tart/vm.go, internal/executor/instance/prebuilt.go, internal/executor/instance/runconfig/runconfig.go, internal/executor/options.go, internal/executor/options/container.go, internal/executor/options/container_test.go, internal/executor/options/tart.go
Resolves https://github.com/cirruslabs/cirrus-cli/issues/510.
=> cirrus run: introduce --lazy-pull flag

internal/commands/run.go, internal/commands/run_test.go, internal/executor/executor.go, internal/executor/executor_test.go, internal/executor/executor_windows_test.go, internal/executor/instance/container/container.go, internal/executor/instance/container/run.go, internal/executor/instance/containerbackend/containerbackend.go, internal/executor/instance/pipe.go, internal/executor/instance/prebuilt.go, internal/executor/instance/runconfig/runconfig.go, internal/executor/instance/volume/volume.go, internal/executor/options.go, internal/executor/options/container_test.go, internal/testutil/containerbackend.go, internal/testutil/executor.go
Very similar to #524 but IMO a bit easier to understand: we initialize a container backend only when we need it.
Fixes https://github.com/cirruslabs/tart/issues/119
=> Initialize container backend lazily

README.md
I'm not even 100% sure but it seems like macos_instances are supported per the README at https://github.com/cirruslabs/tart?
=> README.md: mention macos_instance support

pkg/parser/boolevator/boolevator_test.go, pkg/parser/boolevator/operator.go
Should help with https://github.com/cirruslabs/cirrus-ci-docs/issues/1016#issuecomment-1157946130.
I don't remember why this was done this way, but we'll need to make sure this doesn't break things for users first.
=> Boolevator: disallow <regular expression> =~ <string> matching

pkg/parser/boolevator/boolevator_test.go
We don't support variable expansion in strings for now.
=> Revert "Extra boolevator test case (#529)"

pkg/parser/node/accessor.go
Currently, the output in Cirrus CI is rather unpleasant to read through when things such as `Write-Output` are used as PowerShell sets `OutputFormat` to `XML` *if* the output of the script is redirected:
https://github.com/PowerShell/PowerShell/blob/bcafe74c174091a0f47cf7a5eeb4bca8aefa8718/src/System.Management.Automation/engine/MinishellParameterBinderController.cs#L208
Programs such as chocolatey use that function a lot which makes its output incredibly hard to read through.
Here's a simple reproduction:
```yaml
windows_task:
windows_container:
image: cirrusci/windowsservercore:2019
install_instructions_script:
- ps: 'Write-Output "string"'
```
Produces output:
```
#< CLIXML
string
<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" …
```
=> Add `-OutputFormat Text` to the `ps:` syntactic sugar

.cirrus.yml
Free up some resources we've now mainly using [Tart](https://github.com/cirruslabs/tart) instead of Parallels.
=> Do not run Parallels isolation tests in cloud

internal/executor/instance/container/run.go, internal/executor/instance/containerbackend/containerbackend.go, internal/executor/instance/containerbackend/docker.go, internal/executor/instance/containerbackend/podman_linux.go
So that it would be possible to run [`docker:dind` examples](https://cirrus-ci.org/guide/docker-builds-on-kubernetes/#how-to).
=> cirrus run: support "privileged: true" for additional containers

internal/executor/platform/platform.go, internal/executor/rpc/rpc.go
The tests will pass once https://github.com/cirruslabs/cirrus-ci-agent/pull/245 is merged and the new agent version is released as `1.85.0`.
=> Bump default agent version to 1.85.0

INSTALL.md
`get` is deprecated:
```
> cd && GO111MODULE=on go get github.com/cirruslabs/cirrus-cli/...
go: go.mod file not found in current directory or any parent directory.
'go get' is no longer supported outside a module.
To build and install a command, use 'go install' with a version,
like 'go install example.com/cmd@latest'
For more information, see https://golang.org/doc/go-get-install-deprecation
or run 'go help get' or 'go help install'.
```
`install` requires version (`@latest`, for example).
=> Update `go` installation method

INSTALL.md
1. I don't know why there are parentheses, they look redundant.
2. Add `cd -` at the end to return to the original directory (after `cd` to home at the begin).
=> Improve command for Go installation

internal/worker/upstream/upstream.go
If there are a lot of task candidates for a persistent worker to run is might take a little longer to load and do the logic.
=> [worker] Increased deadline timeout for unary calls to upstream

internal/executor/instance/persistentworker/isolation/tart/vm.go
In case of registry being down we'll continue execution with already pulled image. And in case image missing then the next `clone` will fail.
Motivated by https://github.com/cirruslabs/tart/issues/277
=> Don't fail fast on `tart pull` failure

internal/executor/instance/persistentworker/isolation/tart/tart.go, internal/executor/instance/persistentworker/isolation/tart/vm.go
So it's easier to debug things like #571
=> Use unique task id in temporary VM name

internal/worker/upstream/upstream.go
While investigating https://github.com/cirruslabs/cirrus-ci-docs/issues/1120 it appeared that occasional slowdowns happen for different reasons: network, load balancer, microservice scaling up and cold startup time, etc. Unfortunately, for some reason the call cancelation is not propogated to the backend properly, so it finishes assigning a task to a worker but worker never gets the assigment.
This timeout is our safeguard in case one of the upstream services like Cirrus CI and Cirrus Runners hangs indefinitely. But we've never seen such behaviour, so it make sense to increase this timeout to some very large value inversely proportional to a very low probability of an upstream hang.
=> Ridiculously large timeout

.golangci.yml, internal/executor/instance/persistentworker/isolation/tart/vm.go
This should help with the Softnet "connection reset by peer" errors.
=> Gracefully terminate Tart VMs

.cirrus.yml
To minimize disk usage on Scaleway's M1 machine with small disk.
=> Use macOS Ventura for tests

internal/executor/instance/persistentworker/isolation/tart/vm.go
Otherwise, Tart reports noisy exceptions fot Sentry
=> Wait for the Tart VM IP on Tart side

internal/worker/worker.go
We should wait for all the upstreams to report empty lists of tasks
=> Fixed waiting logic in pause command

.cirrus.yml, cmd/cirrus/main.go
Similarly to how it was done in the agent: https://github.com/cirruslabs/cirrus-ci-agent/pull/264.
=> Use Sentry releases

pkg/parser/bfunc.go, pkg/parser/bfunc_test.go
If a file was matched by two patterns than I was counted multiple times which was leading to incorrect behaviour of `changesIncludeOnly`
=> Fixed counting of matched affected files

pkg/larker/fs/git/git.go, pkg/larker/resolver/module_fs_test.go
Because go-got returns a "no err" in case there is nothing new to fetch.
=> Fixed `failed to retrieve a Git repository: already up-to-date`

internal/executor/platform/platform.go, internal/executor/rpc/rpc.go
Merge after https://github.com/cirruslabs/cirrus-ci-agent/pull/291 gets merged and released as `1.106.0`.
See https://github.com/cirruslabs/cirrus-cli/issues/620#issuecomment-1556779772.
=> Bump agent to 1.106.0 and render agent's warnings and errors received from RPC

pkg/parser/instance/proto.go, pkg/parser/parser_test.go, pkg/parser/testdata/proto-instance-invalid.yml
When enum value can't be found.
Fixes https://github.com/cirruslabs/cirrus-ci-docs/issues/1169
=> Improve proto parser error message

pkg/larker/loader/loader.go
Should improve UX by helping users better diagnose what's exactly not found in their Starlark module repository.
=> Starlark loader: show path when module loading fails due to "not found"

.cirrus.yml, cmd/cirrus/main.go, go.mod, go.sum, internal/worker/upstream/upstream.go, pkg/executorservice/executorservice.go, pkg/larker/loader/loader.go
1. Use `x509.SetFallbackRoots` to prefer the OS-provided CA certificate store over some static set of certificates we've got through a package dependency that had chosen some arbitrary CA set to use and needs to be updated periodically both on our side and on the side of the package.
This change simplifies the code greatly by only requiring a single `x509.SetFallbackRoots()` call in each `main` package, and in our case we only need one such call.
The only downside of this approach is that if the operating-system's CA certificate store is not empty and some of the certificates are outdated, the connection might fail.
4. Switch away from [`github.com/certifi/gocertifi`](github.com/certifi/gocertifi) because [it hasn't been maintained for more than 2 …
=> Use x509.SetFallbackRoots and switch away from gocertifi

internal/executor/instance/persistentworker/isolation/tart/tart.go, internal/worker/task.go
Unfortunately [`sentry-go` doesn't support attachments](https://github.com/getsentry/sentry-go/issues/574), so let's just log a potentially large dump as extra data and hope for the best effort on Sentry web UI's side.
=> Log Softnet status and stacktraces of all goroutines on executor error

internal/executor/rpc/rpc.go
Similar to https://github.com/cirruslabs/cirrus-cli/pull/632.
=> Executor: use proper format string when logging logs

.cirrus.yml, go.mod, go.sum, internal/executor/executor_windows_test.go, internal/worker/task.go
Also use the [new attachments API](https://github.com/getsentry/sentry-go/pull/670) to upload stacktraces.
=> Send stacktrace to Sentry when RPC call results in a deadline

internal/executor/instance/runconfig/runconfig.go
In Persistent Worker, for each task we were initializing a new echelon logger, and it had created a new logging goroutine that wasn't terminated:
```
goroutine 827 [chan receive, 19910 minutes]:
github.com/cirruslabs/echelon.(*Logger).streamEntries(0x140001d4b00, {0x1012aee60, 0x101b489c0})
/go/pkg/mod/github.com/cirruslabs/echelon@v1.9.0/logger.go:74 +0x40
created by github.com/cirruslabs/echelon.NewLogger in goroutine 826
/go/pkg/mod/github.com/cirruslabs/echelon@v1.9.0/logger.go:52 +0x110
goroutine 1313 [chan receive, 19688 minutes]:
github.com/cirruslabs/echelon.(*Logger).streamEntries(0x140001d4940, {0x1012aee60, 0x101b489c0})
/go/pkg/mod/github.com/cirruslabs/echelon@v1.9.0/logger.go:74 +0x40
created by github.com/cirruslabs/echelon.NewLogger in goroutine 1274 …
```
=> Plug goroutine leak

internal/worker/task.go
Unfortunately, `golang.org/x/crypto/ssh` [does not support `context.Context`](https://github.com/golang/go/issues/20288) and when we close `*ssh.Client` in the [monitor's snippet](https://github.com/cirruslabs/cirrus-cli/blob/fec82422350e7f45e59511f2b25609b16c6d1d3a/internal/executor/instance/persistentworker/remoteagent/remoteagent.go#L72-L77) due to context cancellation, we can get pretty much all sorts of random errors, depending on which stage the SSH connection was in, but we won't get the `context.Canceled` which we already try to filter out.
I think the simplest way to work around this is to additionally check if we've actually canceled the context, and if so — ignore the error from the underlying code.
=> Worker: do not report the task as failed if it's context was canceled

internal/commands/run.go, internal/commands/run_darwin_test.go, internal/executor/executor.go, internal/executor/instance/persistentworker/isolation/tart/cmd.go, internal/executor/options.go, internal/worker/worker.go
Also do not attempt to cleanup Tart VMs if Tart is not installed to prevent unactionable warnings.
Resolves https://github.com/cirruslabs/cirrus-cli/issues/656.
=> Executor: only check for heartbeats if --heartbeat-timeout was given

INSTALL.md, README.md
Installing Cirrus CLI package in Debian 12 and Fedora 38 seems to be working great, there are some nits to improve related to https://github.com/cirruslabs/cirrus-cli/pull/658, however.
=> Improve installation docs

Dockerfile
```
% docker run -it --rm ghcr.io/cirruslabs/cirrus-cli:v0.106.1
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/usr/local/bin/cirrus": stat /usr/local/bin/cirrus: no such file or directory: unknown.
```
=> Dockerfile: use correct path to "cirrus" binary

internal/executor/instance/persistentworker/isolation/vetu/vetu.go
=> Vetu isolation: assume VM's architecture is the same as the host's one

go.mod, go.sum, internal/evaluator/evaluator.go, internal/testutil/api.go
Let's use the old-way of instantiating a FS from environment variables for now, will switch to https://github.com/cirruslabs/cirrus-cli/pull/629 later.
=> Evaluator: instantiate a filesystem for running Cirrus Hooks

internal/executor/instance/persistentworker/isolation/tart/tart.go, internal/executor/instance/persistentworker/isolation/tart/vm.go, internal/executor/instance/persistentworker/isolation/vetu/vetu.go, internal/executor/instance/persistentworker/isolation/vetu/vm.go
This way when the configuration fails, we will still cleanup the cloned VM to prevent disk space growth.
=> Vetu instance: separate configuration from cloning

.goreleaser.yml
For some reason #658 removed `brew` release
=> Revert releasing to Homebrew

go.mod, internal/evaluator/evaluator.go, internal/worker/upstream/upstream.go
They seem to generate an insane amount of metrics (e.g. `rpc_client_responses_per_rpc_bucket`) that we don't need.
Let's only keep the tracing enabled.
=> Disable gRPC metrics

go.mod, go.sum, pkg/larker/fs/github/github.go
Use a single instance with tweaked defaults across all the invocations. Plus use newer API of `go-github` (including https://github.com/google/go-github/pull/3011 fix).
Previously a default client was used which doesn't have nor request timeout nor idle connection timeout. This resulted in poor `p99` performance since sometimes connections were hanging blocking others to access `github.com`.
=> Optimize HTTP client used for GitHub

internal/opentelemetry/opentelemetry.go
When not specified, the interval defaults to 60 seconds.
Should help with the [DPM usage](https://grafana.com/docs/grafana-cloud/cost-management-and-billing/understand-your-invoice/metrics-invoice/#billing-calculations).
=> OpenTelemetry: do not export metrics each second

internal/opentelemetry/opentelemetry.go, internal/worker/upstream/upstream.go
Seems there is no need for the client side metrics. Cloud Run gives us a pretty good server side observability.
Plus included architecture in attributes to distinguish vetu hosts.
=> Disable client side gRPC metrics

internal/executor/instance/persistentworker/isolation/tart/tart.go
If the `(*Tart).bootVM()` terminates before the `tart.vm` is set at the end of it (this can happen on context deadline/cancellation, for example), `(*VM).Close()` won't cleanup the Tart VM because it early-exits on `tart.vm == nil`.
=> Tart executor: set tart.vm earlier to prevent Close() race

internal/commands/run.go
resolves #712
Cool thing is that `--env` inside `only_if`s are taken into account. My two tasks (shown in the video below) both have `only_if = "$CIRRUS_TAG =~ 'v.*' || $CIRRUS_BRANCH == 'master'"` (in Starlark) and if I don't type `--env CIRRUS_BRANCH=master` in the command-line invocation, completions are not shown.
https://github.com/cirruslabs/cirrus-cli/assets/40357511/277539cb-2b2e-4fe4-afe4-a03466c582a6
(keys on video shown thanks to [Keycastr](https://github.com/keycastr/keycastr))
=> cirrus run: implement shell completion for task names

internal/executor/instance/persistentworker/isolation/tart/hook.go, internal/executor/instance/persistentworker/isolation/tart/tart.go, internal/executor/instance/persistentworker/isolation/tart/vm.go
To avoid issues with spaces in "/Volumes/My Shared Files".
Also makes `cirrus run` respect `--{,tart-}lazy-pull` for non-standby Tart instances.
Resolves https://github.com/cirruslabs/cirrus-cli/issues/720.
=> Tart: mount the working directory to $HOME when --dirty is specified

cmd/cirrus/main.go, internal/agent/main.go, internal/worker/worker_test.go
Without this the agent seems to ignore any flags.
=> Properly separate the os.Args for the agent

internal/executor/instance/persistentworker/isolation/tart/vm.go
=> Tart executor: always pass --no-clipboard to "tart run"

.cirrus.yml, .goreleaser.yml
CGO was not enabled, and when enabled, we have to use macOS to build the binaries (otherwise macOS headers won't be found in a Linux container).
=> Fix CGO build for Darwin binaries

.ci/remove-signature.sh, .goreleaser.yml
To prevent the `unable to remove existing code signature: code signing command is not the last loader command, so cannot remove it (easily) without corrupting the binary` error [from Quill](https://github.com/anchore/quill/commit/5b8e07f50a58c3493c277936f1b0754b749cf468).
=> .goreleaser.yml: remove binary signatures before notarizing

internal/executor/instance/container/container.go, internal/executor/instance/containerbackend/podman_linux.go, internal/executor/instance/pipe.go, internal/executor/instance/prebuilt.go
We were only calling instance's `Close()`, but not container backend's `Close()`.
Also, Podman expects a `SIGTERM`, not `SIGINT`, otherwise exit code won't be `0` and we'll error out.
Resolves https://github.com/cirruslabs/cirrus-cli/issues/766.
=> Plug container backend's Close() into instance's Close()

internal/agent/executor/executor.go
Instead of just reporting that a step finished. This will simplify looking into agent logs.
=> Log command status from the agent

.cirrus.yml
Could help with TestWorkerStandByVetu timing out after 10 minutes.
=> Pre-pull Vetu VM before running tests

internal/agent/http_cache/ghacache/ghacache.go
Otherwise, GHA Runners can get 404 on a retry
=> [gha cache] delete on success only

go.mod, go.sum, internal/executor/instance/containerbackend/podman_linux.go
To fix the Podman-specific tests failing.
=> Podman container backend: ignore exit codes on Podman versions <4.1.0

internal/agent/http_cache/ghacache/ghacache.go
And pass-through other errors that Actions Toolkit deems as retryable.
=> GHA cache: handle io.EOF when uploading a part

go.mod, go.sum, internal/agent/http_cache/ghacache/ghacache.go, internal/agent/http_cache/http_cache.go
And also move towards structured logging a bit more by parametrizing the failure attributes.
Looks like this (note the `url`, which [`github.com/getsentry/sentry-go/http`](https://pkg.go.dev/github.com/getsentry/sentry-go/http) package provides:
And this:
=> GHA cache: report failures to Sentry

.goreleaser.yml
These builds take space and I haven't heard from anyone running Cirrus CLI on Solaris nor ppc64. If you fall into this category, please let us know 🙌 
We had someone use Cirrus CLI on `linux` + `s390x`, though, so keeping this combo for now.
=> .goreleaser.yml: disable Solaris and ppc64 builds

internal/commands/worker/config.go, internal/executor/instance/persistentworker/isolation/tart/tart.go, internal/worker/options.go, internal/worker/worker.go
Can be configured as follows:
```yaml
tart-pre-pull:
- ghcr.io/cirruslabs/macos-runner:sonoma
- ghcr.io/cirruslabs/macos-runner:sequoia
```
Only works when standby is configured and only triggers before the standby creation/re-creation.
=> Persistent Worker: allow pre-pulling specified Tart VMs periodically

internal/commands/worker/run.go, internal/executor/agent/agent.go, internal/executor/instance/persistentworker/isolation/none/none.go, internal/executor/instance/persistentworker/isolation/parallels/cli.go, internal/executor/instance/persistentworker/isolation/tart/cmd.go, pkg/privdrop/common.go, pkg/privdrop/privdrop.go, pkg/privdrop/privdrop_unsupported.go
Compared to https://github.com/cirruslabs/cirrus-cli/pull/814.
Closes https://github.com/cirruslabs/cirrus-cli/pull/814.
=> A much more lax approach to privelege separation

internal/agent/cirrusenv/cirrusenv_windows_test.go, internal/executor/agent/agent.go, internal/executor/instance/persistentworker/pwdir/pwdir.go
=> Call os.Chown() in the right place when creating a static directory

internal/worker/prepull.go, internal/worker/prepull_test.go
So that when multiple Persistent Workers are started around the same time, the pre-pull will still commence at slightly different times on these workers.
=> Pre-pull: implement jitter

buf.gen.yaml
See https://cirrus-ci.com/task/5677166123286528.
Need to release `v0.136.0` after this.
=> buf.gen.yaml: use versioned remote plugins to avoid surprises

internal/agent/http_cache/azureblob/blockid.go, internal/agent/http_cache/azureblob/blockid_test.go, internal/agent/http_cache/azureblob/putblob.go
The former approach is too error-prone and without this change results in "received a block list pointing to a non-existent block" because of a missing "+ 1" when calling `GetPart()` in `putBlockList()`.
=> blockIDToIndex → blockIDToPartNumber

.golangci.yml, internal/agent/main.go, internal/executor/instance/persistentworker/remoteagent/remoteagent.go
To get Sentry events for potential GHA cache v2 errors.
See https://github.com/cirruslabs/cirrus-cli/pull/790#pullrequestreview-2327970226.
=> Propagate SENTRY_DSN to agent running in Tart/Vetu

internal/agent/targz/targz.go, internal/agent/targz/targz_test.go
This way symbolic links pointing to a path that starts with a base directory will continue to work after `Unarchive()`, because these symbolic links will point to location relative to their own location.
Right now they are made relative to the base directory, which is only correct when such a link resides in that base directory.
=> Agent(targz): make symlink targets relative to their current directory

internal/agent/http_cache/azureblob/getblob.go, internal/agent/progressreader/progressreader.go, internal/agent/progressreader/progressreader_test.go
I think we can further improve the implementation by re-using the `io.CopyBuffer`'s logic and supplying our own `io.Reader` that wraps the original one.
=> Introduce "progressreader" package for composable cache download logging

.golangci.yml, internal/agent/executor/executor.go, internal/agent/http_cache/azureblob/azureblob.go, internal/agent/http_cache/azureblob/getblob.go, internal/agent/http_cache/azureblob/headblob.go, internal/agent/http_cache/ghacache/ghacache_test.go, internal/agent/http_cache/ghacachev2/ghacachev2_test.go, internal/agent/http_cache/http_cache.go, internal/agent/http_cache/http_cache_test.go, internal/agent/http_cache/tuistcache/tuistcache_test.go, internal/agent/main.go
Also adapted `.golangci-lint.yml` to golangci-lint 2.0.
=> Agent(http_cache/azureblob): do not set Content-Length when Chacha is on

internal/agent/executor/executor.go
Also pick up `CIRRUS_CHACHA_{ADDR,CERT}` from OS environment variables instead of executor's environment.
=> Agent: fix inverted logic used to enable Chacha

README.md
To explain the "Local Network" workaround [that we now have](https://github.com/cirruslabs/cirrus-cli/pull/891).
=> README.md: add macOS Sequoia note

internal/worker/worker.go
Otherwise we get `connect: no route to host` error.
=> Worker: ensure that worker.localNetworkHelper is passed to Warmup()

internal/worker/task.go
`agentAwareTask.Traceparent` and `agentAwareTask.Tracestate` can be empty, which will result in agent not configuring it's trace context.
By using `Inject()` and reading results from the `mapCarrier`, we always get some kind of trace context.
=> Persistent Worker: fix context propagation to the agent

internal/executor/platform/platform.go
Could help with https://github.com/cirruslabs/cirrus-cli/issues/882.
By fixing https://github.com/cirruslabs/cirrus-cli/pull/801, for example.
=> Bump default agent version from 0.127.1 to 0.143.2

internal/worker/upstream/upstream.go, internal/worker/worker.go
`SetDisabled()` converts the gRPC's `err` into string when returning it, so using `status.FromError()` on that `err` makes no sense.
To fix this we simply apply DRY and handle the `NOT_FOUND` in `SetDisabled()` by returning `nil`.
Introduced in https://github.com/cirruslabs/cirrus-cli/pull/911.
=> Worker: fix gRPC's NOT_FOUND error handling

internal/agent/http_cache/azureblob/azureblob.go
It turns out that the [github.com/tonistiigi/go-actions-cache](https://github.com/tonistiigi/go-actions-cache) library, which BuildKit uses, [expects an optional `RequestID` field](https://github.com/tonistiigi/go-actions-cache/blob/378c5ed1ddd9f4bd9371b02deeca46c9b6fae2fa/cache_v2.go#L74), which is based on `x-ms-request-id` header that we don't currently set, which causes NPE and a this weird error.
P.S. this was discovered using BuildKit logs, which can be enabled like this:
```yaml
uses: docker/setup-buildx-action@v3
with:
buildkitd-flags: --debug
```
=> http_cache(azureblob): fix buildkit crash w/ "failed to receive status"

internal/agent/http_cache/azureblob/putblob.go, internal/agent/http_cache/azureblob/uploadable/uploadable.go, internal/agent/http_cache/ghacachev2/ghacachev2_test.go
To work around [github.com/tonistiigi/go-actions-cache](https://github.com/tonistiigi/go-actions-cache) use 1 MiB chunks [by default](https://github.com/tonistiigi/go-actions-cache/blob/378c5ed1ddd9f4bd9371b02deeca46c9b6fae2fa/cache_v2.go#L70).
=> http_cache(azureblob): local uploadable functionality for small chunks

internal/agent/http_cache/ghacache/cirruscimock/cirruscimock.go, internal/agent/http_cache/ghacachev2/ghacachev2.go
We already have `url.PathEscape()` in `azureBlobURL()`.
Otherwise [this part of `github.com/tonistiigi/go-actions-cache`](https://github.com/moby/buildkit/blob/a23bc16feff9789f207a7b59220ce79c86444a39/vendor/github.com/tonistiigi/go-actions-cache/cache.go#L440-L443) fails.
=> ghacachev2: do not escape cache key when not necessary

internal/executor/instance/persistentworker/remoteagent/remoteagent.go
Otherwise we may wait more than needed (e.g. 30 seconds<sup>1</sup>) due to an exponential backoff.
<sup>1</sup>: trace IDs `cee3874c750c135273f54d25d708ba4d`, `8d80220baf01a503d2460bd8163c6ac6`, etc.
=> remoteagent: use bounded context when dialing in WaitForSSH()

internal/agent/http_cache/azureblob/putblob.go
Headers are pre-signed too, so ensure that they're present, otherwise we'll get HTTP 403.
=> azureblob(putblob): propagate headers from GenerateCacheUploadURL()
